<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >ÁREA RESTRITA</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
    
    <div class="container" style="text-align: center;" >
            <h4>Atalhos</h4>
            <hr>
    </div>
	
	
    <div class="container">

        <div class="row justify-content-md-center">

            <div class="col-md-auto mb-5">
                <a href="/" >
                    <div class="gmd gmd-1 font-shadow">
                        <img src="images/painel.png" class="img-rounded" alt="Cinque Terre">
                        <p>Gestão à vista Pedidos</p>
                    </div>
                </a>
            </div>

            <div class="col-md-auto mb-5">
                <a href="/" >
                    <div class="gmd gmd-1 font-shadow">
                        <img src="images/new_order.png" class="img-rounded" alt="Cinque Terre" style="width: 50px">
                        <p>Novo Pedido</p>
                    </div>
                </a>
            </div>

            <div class="col-md-auto mb-5">
                <a href="/" >
                    <div class="gmd gmd-1 font-shadow">
                        <img src="images/add_customer.png" class="img-rounded" alt="Cinque Terre">
                        <p>Cadastro de Cliente</p>
                    </div>
                </a>
            </div>

        </div>


        <div class="row justify-content-md-center">

            <div class="col-md-auto mb-5">
                <a href="/" >
                    <div class="gmd gmd-1 font-shadow">
                        <img src="images/menu.png" class="img-rounded" alt="Cinque Terre" style="width: 50px">
                        <p>Cardápio no site</p>
                    </div>
                </a>
            </div>

            <div class="col-md-auto mb-5">
                <a href="/" >
                    <div class="gmd gmd-1 font-shadow">
                        <img src="images/relatorio.png" class="img-rounded" alt="Cinque Terre">
                        <p>Relatório Vendas</p>
                    </div>
                </a>
            </div>

        </div>

    </div>	  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
</div>




















