<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="assets/css/login.css">

    <link rel="icon" href="images/favicon.ico">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <title>Login - Jazz Grill</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
    <div class="container">
        <a class="brand" href="/">
            <img class="brand-logo-dark" src="images/logo-198x66.png" alt="" width="198" height="66"/>
        </a>
    </div>
</nav>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Login</div>
                    <div class="card-body">
                        
                            <div class="form-group row">
                                <label for="email_address" class="col-md-4 col-form-label text-md-right">ENTROU MANO</label>
                               
                            </div>

                            
                    </div>
                  
                </div>
            </div>
        </div>
    </div>
    </div>

</main>


        <form action="/login/valida_login" method="POST" id="form_cadastra_new_adm">
            <input type='hidden' name="email"       id="email">
            <input type='hidden' name="nome"        id="nome">
            <input type='hidden' name="telefone"    id="telefone">
        </form>




</body>
</html>