
<div style="background-image: linear-gradient(#EEE, #FDFdFd);">

<hr>

<div class="" >
    <nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
        <div class="container">
            <a class="brand" href="/">
                <img class="brand-logo-dark" src="/images/logo-198x66.png" alt="" width="198" height="66"/>
            </a>
        </div>
    </nav>
</div>




<!-- Page Footer-->
      <footer class="section footer-modern context-dark footer-modern-2">
       
        
        <div class="footer-modern-line-3">
          <div class="container">
            <div class="row row-10 justify-content-between">
              <div class="col-md-6"><span>Vila Velha - ES</span></div>
              <div class="col-md-auto">
                <!-- Rights-->
                <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span><span></span><span>.&nbsp;</span><span>All Rights Reserved.</span><span> Design&nbsp;by&nbsp;<a href="#">Paulo Franco</a></span></p>
              </div>
            </div>
          </div>
        </div>
      </footer>


</div>



