<!--Cabecalho-->
<div class="container border text-center"  style="background: #FAFAFA">
    <div class="form-row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <img class="brand-logo-dark" src="/images/logo-198x66.png" alt="" width="198" height="66"/>
        </div>
        <div class="col-md-1">
            <a   class="btn btn-light " onClick="window.print()" role="button"><span class='glyphicon glyphicon-print' ></span></a>
        </div>
    </div>
    <h5><strong>Relatório de Clientes X Compras</strong></h5>
    <i>Período <?= $this->view->periodo?></i>
</div>


<!--Resumo-->
<div class="container border mt-1"  style="background: #FAFAFA">
    <div class="form-row text-center mt-2">
        <div class="col-md-6"> <h3> Quantidade de Vendas: <?= $this->view->qtd_pedidos ?> </h3></div>
        <div class="col-md-6"> <h3>Valor total: R$        <?= $this->view->valor_pedidos ?>   </h3> </div>
    </div>
</div>



<!--Relacao de pedidos-->
<div class="container border mt-1">
    
    <div class="form-row border mt-2">
        <div class="col-md-1 text-center"> <strong>    ID  </strong></div>
        <div class="col-md-2 text-left">   <strong>    NOME  </strong></div>
        <div class="col-md-1 text-center"> <strong>    VALOR  </strong></div>
        <div class="col-md-2 text-center"> <strong>    DATA  </strong></div>
        <div class="col-md-2 text-center"> <strong>    STATUS  </strong></div>
        <div class="col-md-1 text-center"> <strong>    PAGO  </strong></div>
        <div class="col-md-1 text-center"> <strong>    Pagamento  </strong></div>
    </div>
    
    <?php
        if($this->view->pedidos->erro == false){
            for ($h=0; $h < sizeof($this->view->pedidos->resultado); $h++){
                ?>
                    <div class="form-row  mt-1">
                        <div class="col-md-1 text-center"> <?= $this->view->pedidos->resultado[$h]->id_order ?>  </div>
                        <div class="col-md-2 text-left">   <?= $this->view->pedidos->resultado[$h]->customer_name ?> </div>
                        <div class="col-md-1 text-center"> R$ <?= \App\Models\Padroes_gerais::ValorDoisDigitos($this->view->pedidos->resultado[$h]->total_pedido) ?> </div>
                        <div class="col-md-2 text-center"> <?= \App\Models\Padroes_gerais::ConverteDataHoraUS_BR($this->view->pedidos->resultado[$h]->created_at) ?>   </div>
                        <div class="col-md-2 text-center"> <?= $this->view->pedidos->resultado[$h]->status_name ?>  </div>
                        <div class="col-md-1 text-center"> <?= $this->view->pedidos->resultado[$h]->payment_status == 1 ? "SIM" : "NÃO"?>  </div>
                        <div class="col-md-1 text-left">   <?= $this->view->pedidos->resultado[$h]->payment_term_name?>  </div>
                    </div>
               <?php
            }
        }else{
           ?>
                <div class="form-row text-center mt-2">
                    <div class="col-md-12"> <i>Não há pedidos a mostrar.</i></div>
                </div>
           <?php
        }
    ?>
</div>


<div class="container border mt-1">
    <div class="form-row mt-2">
        <div class="col-md-6 text-left"> <i> Jazz Grill Burger</i></div>
        <div class="col-md-6 text-right"> <i>Impresso em  <?= \App\Models\Padroes_gerais::Hoje() ?>   </i> </div>
    </div>
</div>


