<!--Cabecalho-->
<div class="container border text-center"  style="background: #FAFAFA">
    <div class="form-row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <img class="brand-logo-dark" src="/images/logo-198x66.png" alt="" width="198" height="66"/>
        </div>
        <div class="col-md-1">
            <a   class="btn btn-light " onClick="window.print()" role="button"><span class='glyphicon glyphicon-print' ></span></a>
        </div>
    </div>
    <h5><strong>Relatório de vendas Completo</strong></h5>
    <i>Período <?= $this->view->periodo?></i>
</div>


<!--Resumo-->
<div class="container border mt-1"  style="background: #FAFAFA">
    <div class="form-row text-center mt-2">
        <div class="col-md-6"> <h3> Quantidade de Vendas: <?= $this->view->qtd_pedidos ?> </h3></div>
        <div class="col-md-6"> <h3>Valor total: R$        <?= $this->view->valor_pedidos ?>   </h3> </div>
    </div>
</div>



<!--Relacao de pedidos-->
<div class="container border mt-1">
    
    
    <?php
        if($this->view->pedidos->erro == true){
            for ($h=0; $h < sizeof($this->view->pedidos->resultado); $h++){
            
            }
        }else{
           ?>
                <div class="form-row text-center mt-2">
                    <div class="col-md-12"> <i>Não há pedidos a mostrar.</i></div>
                </div>
           <?php
        }
    ?>
    
    
    
    
</div>





<div class="form-row text-center mt-2">
        <div class="col-md-6"> <h3> Quantidade de Vendas: <?= $this->view->qtd_pedidos ?> </h3></div>
        <div class="col-md-6"> <h3>Valor total: R$        <?= $this->view->valor_pedidos ?>   </h3> </div>
    </div>