<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >RELATÓRIOS</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
	
    
    <div class="container">
        
        <!--filtro Data-->
        <div class="" id="filter_data">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp;&nbsp;Data Inicial</span>
                        </div>
                        <input class="form-control" id="txt_data_inicial" name="date" placeholder="" type="text"/>
                <div class="invalid-feedback">Digite alguma data.</div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp;&nbsp;Data Final</span>
                        </div>
                        <input class="form-control" id="txt_data_final" name="date" placeholder="" type="text"/>
                    </div>
                </div>
            </div>   
        </div>
        

        <hr>
        
        
        <!--Tipo busca COMPLETA / FILTRO PARCIAL-->
        <div class="col-6 mt-3">
            <div class="row">&nbsp Tipo de busca</div>
            <div class="row">
                    <div class=" col-sm">
                        <a class="btn btn-success btn-block text-white" id="ativo_sim" role="button">Todas as vendas</a>
                    </div>
                    <div class="col-sm">
                        <a class="btn btn-outline-info btn-block" id="ativo_nao" role="button">Vendas Específicas</a>
                    </div>
            </div>
        </div>
        
        
        <hr>
        
        
        
        
        
        <!--Todas as vendas-->
        <div class="form-row">
            <div class="form-group col-md-12">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <button class="btn btn-dark" type="button">Todas as vendas</button>
                    </div>
                    <input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
                </div>
            </div>
	</div>
        
        
        
        <!--Todas as vendas-->
        <div class="form-row">
            <div class="form-group col-md-12">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <button class="btn btn-outline-secondary" type="button">Todas as vendas</button>
                    </div>
                    <input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
                </div>
            </div>
	</div>
        
        
        
        <!--Todas as vendas-->
        <div class="form-row">
            <div class="form-group col-md-12">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <button class="btn btn-outline-secondary" type="button">Todas as vendas</button>
                    </div>
                    <input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
                </div>
            </div>
	</div>
        
        
        
        
        
        
        
        
        
        
        
        
        
        
  

        <!--NOME-->
        <div class="form-row">
            <div class="form-group col-md-12">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"> 
                        </div>
                    </div>
                    <input type="text" class="form-control" aria-label="Text input with checkbox">
                </div>
            </div>
	</div>
        
        
        
        <hr>
        
        <!--VALIDAR e SEGUIR-->
        <div class="form-row mb-4 mt-3">
            <a id="btn_validar" name="btn_validar" class="btn btn-success btn-lg btn-block text-white" role="button">Consultar</a>
        </div>
    </div>
</div>





<!--form salvar-->
    <form action="/cadastrar_novo_adm" method="POST" id="cadastrar_novo_item">
        <input type='hidden'    name="name"                      id="name">
        <input type='hidden'    name="email"                     id="email">
        <input type='hidden'    name="obs"                       id="obs">
    </form>
















