
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    

    <link rel="icon" href="images/favicon.ico">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/css/login.css">
    <link rel="stylesheet" href="assets/css/bootstrap.css">

    
    <title>Login - Jazz Grill</title>
</head>
<body>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header text-center">
                        <img class="brand-logo-dark" src="images/logo-198x66.png" alt="" width="198" height="66"/>
                    </div>
                    <div class="card-body">
                        

                        
                            <div class="form-group row">
                                <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail</label>
                                <div class="col-md-6">
                                    <input type="text" id="txt_email" class="form-control" name="email-address" value="<?php echo (isset($this->inputs['email'])) ? $this->inputs['email'] : '' ?>" required autofocus>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Senha</label>
                                <div class="col-md-6">
                                    <input type="password" id="txt_password" class="form-control" name="password" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember" id="remember"> Lembrar
                                        </label>
                                    </div>
                                </div>
                            </div>
                            

                            <div class="col-md-6 offset-md-4" id="show_btn">
                                <a class="btn btn-outline-info" href="#" id="btn_entrar" role="button">  
                                    <span class="esconder" id="" role="status" aria-hidden="true"></span>
                                    Entrar
                                </a>
                            </div>
                            <div class="esconder" id="show_load">
                                <a class="btn btn-warning disabled" href="#" id="btn_entrar" role="button">  
                                    <span class="spinner-border spinner-border-sm" id="" role="status" aria-hidden="true"></span>
                                    Carregando...
                                </a>
                            </div>
                    </div>
                  
                </div>
            </div>
        </div>
        
        
        
        
        
        
    </div>
    </div>

</main>


        <form action="/login/valida_login" method="POST" id="form_valida_login">
            <input type='hidden' name="email"           id="email">
            <input type='hidden' name="password"        id="password">
            <input type='hidden' name="keep_conected"   id="keep_conected">
        </form>


    
    
    <!-- Javascript-->
    
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/popper.min.js" crossorigin="anonymous"></script>
    <script src="/assets/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="/assets/js/adm/login/login.js" crossorigin="anonymous"></script>
    


</body>
</html>