<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >NOVO CLIENTE</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
	
    
    <div class="container">
        
        <!--Telefones-->
        <div class="form-row">
            <!--Telefones-->
            <div class="form-group col-md-6">
                    <label for="inputState">Telefones</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Principal</span>
                        </div>
                        <input type="text" class="form-control" id="txt_telefone_1" name="txt_telefone_1" placeholder="(99) 9 9999-9999" aria-label="Telefone" aria-describedby="basic-addon1">
                        <div class="valid-feedback">Número Válido!</div>
                        <div class="invalid-feedback">Número já cadastrado!</div>
                    </div>
            </div>
            
            <div class="form-group col-md-6">
                    <label for="inputState">.</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Secundário</span>
                        </div>
                        <input type="text" class="form-control" id="txt_telefone_2" name="txt_telefone_2" placeholder="(99) 9 9999-9999" aria-label="Telefone" aria-describedby="basic-addon1">
                        <div class="valid-feedback">Número Válido!</div>
                        <div class="invalid-feedback">Número já cadastrado!</div>
                    </div>
            </div>
	</div>
        
        
        
        <!--NOME-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Nome</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Nome</span>
                        </div>
                        <input type="text" class="form-control" id="txt_name" name="txt_name" placeholder="" aria-label="Telefone" aria-describedby="basic-addon1">
                        <div class="valid-feedback">Nome valido.</div>
                        <div class="invalid-feedback">Digite o nome.</div>
                    </div>
            </div>
	</div>
        
        
        <!--CPF-->
        <div class="form-row">
            <div class="form-group col-md-6">
                    <label for="inputState">CPF (opcional)</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">CPF</span>
                        </div>
                        <input type="text" class="form-control" id="txt_cpf" name="txt_cpf" placeholder="" aria-label="Telefone" aria-describedby="basic-addon1">
                    </div>
            </div>
	</div>
        
        
        <!--Observacoes-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <div class="form-group">
                    <label for="exampleFormControlTextarea1">Observações</label>
                    <textarea class="form-control" id="txt_obs_customer" rows="3"></textarea>
                  </div>
            </div>
	</div>
        
        
        
        <hr>
        <!-- Button trigger modal -->
        
        <div class="form-row">
            <div class="form-group col-md-6">
                <div class="input-group mb-3">
                    <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#add_address">
                        Endereço 1
                    </button>
                </div>
                
                
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <p id="p_end_1_1"></p>
                        <p id="p_end_1_2"></p>
                    </div>
               </div>
                
                
                
                
            </div>
            <div class="form-group col-md-6">
                <div class="input-group mb-3">
                    <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#add_address2">
                        Endereço 2
                    </button>
                </div>
            </div>
        </div>
        
        
        
        <!--ENDERECO 1-->
        <div class="modal fade" id="add_address" data-keyboard="false" >
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document" >
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Adicionar endereço 1</h5>
                    </div>
                    <div class="modal-body">
                        
                        <!--Tipo-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Tipo de Endereço</span>
                                    </div>
                                    <input type="text" class="form-control" id="tipo" name="tipo" placeholder="" aria-label="tipo" aria-describedby="basic-addon1">
                                </div>
                            </div>
                        </div>

                        <!--Cep-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Cep</span>
                                    </div>
                                    <input type="text" class="form-control" id="cep" name="cep" placeholder="" aria-label="CEP"  onblur="pesquisacep(this.value);"  aria-describedby="basic-addon1">
                                </div>
                            </div>
                        </div>
                        
                        <!--Rua-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Rua</span>
                                    </div>
                                    <input type="text" class="form-control" id="rua" name="rua" placeholder="" aria-label="CEP"   aria-describedby="basic-addon1">
                                </div>
                            </div>
                        </div>
                        
                        <!--Numero Bairro-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Número e complemento</span>
                                    </div>
                                    <input type="text" class="form-control" id="numero" name="numero" placeholder="" aria-label="numero"   aria-describedby="basic-addon1">
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Bairro</span>
                                    </div>
                                    <input type="text" class="form-control" id="bairro" name="bairro" placeholder="" aria-label="Bairro"   aria-describedby="basic-addon1">
                                </div>
                            </div>
                        </div>
                        
                        <!--Cidade Estado-->
                        <div class="form-row">
                            <div class="form-group col-md-8">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Cidade</span>
                                    </div>
                                    <input type="text" class="form-control" id="cidade" name="cidade" placeholder="" aria-label="numero"   aria-describedby="basic-addon1">
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Estado</span>
                                    </div>
                                    <input type="text" class="form-control" id="uf" name="uf" placeholder="" aria-label="numero"   aria-describedby="basic-addon1">
                                </div>
                            </div>
                        </div>
                       
                        <!--Ponto de referentia-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Ponto de referência</span>
                                    </div>
                                    <input type="text" class="form-control" id="referencia" name="referencia" placeholder="" aria-label="numero"   aria-describedby="basic-addon1">
                                </div>
                            </div>
                        </div>
                        
                        <!--Observacoes-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                    <div class="form-group">
                                    <label for="exampleFormControlTextarea1">Observações</label>
                                    <textarea class="form-control" id="txt_obs_endereco_1" rows="3"></textarea>
                                  </div>
                            </div>
                        </div>
                        
                        <div class="modal-footer">
                            <div class="form-row mb-4 mt-3">
                                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Sair sem salvar</button>
                            </div>
                            <!--VALIDAR e SEGUIR-->
                            <div class="form-row mb-4 mt-3">
                                <a id="btn_salvar_end_1" name="btn_salvar_end_1" class="btn btn-outline-success" href="#" role="button">Salvar</a>
                            </div>
                        </div>
                        
                        
                        
                    </div>
                </div>
            </div>
        </div>
        
        
        
        <hr>
        
        
        
        
        


        
        
        
        <div class="esconder" role="alert" id="msg_questao_repetida">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <p><i class="glyphicon glyphicon-alert"></i> Esta questão já existe em nosso banco de dados. Por favor, insira outra.</p>
        </div>
        
        
        <!--VALIDAR e SEGUIR-->
        <div class="form-row mb-4 mt-3">
            <a id="btn_validar" name="btn_validar" class="btn btn-outline-danger btn-lg btn-block disabled" href="#" role="button">Salvar</a>
        </div>
        
        
    </div>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
</div>




















