<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >EDITAR CLIENTE</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
	
    
    <div class="container">
        
        
        <!--ID e ATIVO-->
        <div class="row mb-2">
                <div class="col-sm">
                    <!--ID-->
                    <div class="form-row">
                        <div class="form-group col-md-6">
                                <label for="inputState">Identificador</label>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">ID</span>
                                    </div>
                                    <input type="text" class="form-control" id="txt_id" name="txt_id" disabled value="<?php echo $this->view->dados_customer->id_customer  ?>" placeholder="" aria-label="Telefone" aria-describedby="basic-addon1" maxlength="14">
                                </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-sm mt-3">
                    <div class="row">&nbsp Usuario Ativo</div>
                    <div class="row">
                            <div class=" col-sm">
                                <a class="<?= $this->view->dados_customer->active == 1 ? "btn btn-success btn-block" : "btn btn-outline-success btn-block"?>" id="ativo_sim" role="button">ATIVO</a>
                            </div>
                            <div class="col-sm">
                                <a class="<?= $this->view->dados_customer->active == 0 ? "btn btn-danger btn-block" : "btn btn-outline-danger btn-block"?>" id="ativo_nao" role="button">INATIVO</a>
                            </div>
                    </div>
                </div>
        </div>
        
        
        
        <!--Telefones-->
        <div class="form-row">
            
            <!--Telefones-->
            <div class="form-group col-md-6">
                    <label for="inputState">Telefones</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">
                                Principal
                                <span class="" id="loading_phone1" role="status" aria-hidden="true"></span>
                            </span>
                        </div>
                        <input type="text" class="form-control" id="txt_telefone_1" name="txt_telefone_1" value="<?php echo $this->view->dados_customer->phone_number_1  ?>" onblur="validaTelefone1(this.value);"  placeholder="(99) 9 9999-9999" aria-label="Telefone" aria-describedby="basic-addon1">
                        <div class="valid-feedback">Número Válido!</div>
                        <div class="invalid-feedback">Número já cadastrado ou inválido!</div>
                    </div>
            </div>
            
            <div class="form-group col-md-6">
                    <label for="inputState">.</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">
                                Secundário
                                <span class="" id="loading_phone2" role="status" aria-hidden="true"></span>
                            </span>
                        </div>
                        <input type="text" class="form-control" id="txt_telefone_2" name="txt_telefone_2" value="<?php echo $this->view->dados_customer->phone_number_2  ?>" onblur="validaTelefone2(this.value);" placeholder="(99) 9 9999-9999" aria-label="Telefone" aria-describedby="basic-addon1">
                        <div class="valid-feedback">Número Válido!</div>
                        <div class="invalid-feedback">Número já cadastrado!</div>
                    </div>
            </div>
	</div>
        
        
        
        <!--NOME-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Nome</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Nome</span>
                        </div>
                        <input type="text" class="form-control" id="txt_name" name="txt_name" value="<?php echo $this->view->dados_customer->name  ?>" onblur="validaNome(this.value);"  placeholder="" aria-label="Telefone" aria-describedby="basic-addon1" maxlength="60">
                        <div class="invalid-feedback">Nome obrigatório.</div>
                    </div>
            </div>
	</div>
        
        
        <!--CPF-->
        <div class="form-row">
            <div class="form-group col-md-6">
                    <label for="inputState">CPF (opcional)</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">CPF</span>
                        </div>
                        <input type="text" class="form-control" id="txt_cpf" name="txt_cpf" value="<?php echo $this->view->dados_customer->cpf  ?>" placeholder="" aria-label="Telefone" aria-describedby="basic-addon1" maxlength="14">
                    </div>
            </div>
	</div>
        
        
        <!--Observacoes-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <div class="form-group">
                    <label for="exampleFormControlTextarea1">Observações</label>
                    <textarea class="form-control" id="txt_obs_customer" rows="3" maxlength="255"><?php echo $this->view->dados_customer->obs  ?></textarea>
                  </div>
            </div>
	</div>
        
        
        
        <hr>
        <!-- ENDERECOS -->
        
        <!--Controles-->
        <div class="form-row">
            <div class="form-group col-md-6">
                <div class="input-group mb-3">
                    <button type="button" class="btn btn-outline-info" id="btn_add_Adress" data-toggle="modal" data-target="#add_address">
                        Endereço 1
                    </button>
                    <div class="invalid-feedback">Endereço obrigatório.</div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <p id="p_end_1_1"></p>
                    </div>
                </div>
            </div>
            
             <div class="form-group col-md-6">
                <div class="input-group mb-3">
                    <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#add_address2">
                        Endereço 2
                    </button>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <p id="p_end_1_2"></p>
                    </div>
                </div>
            </div>
        </div>
        
        
        
        <!--ENDERECO 1-->
        <div class="modal fade" id="add_address" data-keyboard="false" >
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document" >
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Adicionar endereço 1</h5>
                    </div>
                    <div class="modal-body">
                        
                        <!--ID-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                    <label for="inputState">Identificador</label>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">ID</span>
                                        </div>
                                        <input type="text" class="form-control" id="txt_id_end1" name="txt_id_end1" disabled value="<?php echo $this->view->dados_customer->end[0]->id_address ?>" placeholder="" aria-label="Telefone" aria-describedby="basic-addon1" maxlength="14">
                                    </div>
                            </div>
                        </div>
                        
                        <!--Tipo-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Tipo de Endereço</span>
                                    </div>
                                    <input type="text" class="form-control" id="tipo" name="tipo" value="<?php echo $this->view->dados_customer->end[0]->local  ?>" aria-label="tipo" aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                        </div>

                        <!--Cep-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Cep</span>
                                    </div>
                                    <input type="text" class="form-control" id="cep" name="cep" value="<?php echo $this->view->dados_customer->end[0]->cep ?>" aria-label="CEP"  onblur="pesquisacep(this.value);"  aria-describedby="basic-addon1">
                                </div>
                            </div>
                        </div>
                        
                        <!--Rua-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Rua</span>
                                    </div>
                                    <input type="text" class="form-control" id="rua" name="rua" value="<?php echo $this->view->dados_customer->end[0]->rua ?>" aria-label="CEP"   aria-describedby="basic-addon1" maxlength="255">
                                </div>
                            </div>
                        </div>
                        
                        <!--Numero Bairro-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Número e complemento</span>
                                    </div>
                                    <input type="text" class="form-control" id="numero" name="numero" value="<?php echo $this->view->dados_customer->end[0]->numero_complemento ?>" aria-label="numero"   aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Bairro</span>
                                    </div>
                                    <input type="text" class="form-control" id="bairro" name="bairro" value="<?php echo $this->view->dados_customer->end[0]->bairro ?>" aria-label="Bairro"   aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                        </div>
                        
                        <!--Cidade Estado-->
                        <div class="form-row">
                            <div class="form-group col-md-8">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Cidade</span>
                                    </div>
                                    <input type="text" class="form-control" id="cidade" name="cidade" value="<?php echo $this->view->dados_customer->end[0]->cidade ?>" aria-label="numero"   aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Estado</span>
                                    </div>
                                    <input type="text" class="form-control" id="uf" name="uf" value="<?php echo $this->view->dados_customer->end[0]->estado ?>" aria-label="numero"   aria-describedby="basic-addon1" maxlength="2">
                                </div>
                            </div>
                        </div>
                       
                        <!--Ponto de referentia-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Ponto de referência</span>
                                    </div>
                                    <input type="text" class="form-control" id="referencia" name="referencia" value="<?php echo $this->view->dados_customer->end[0]->referencia ?>" aria-label="numero"   aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                        </div>
                        
                        <!--Observacoes-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                    <div class="form-group">
                                    <label for="exampleFormControlTextarea1">Observações</label>
                                    <textarea class="form-control" id="txt_obs_endereco_1"  rows="3" maxlength="60"><?php echo $this->view->dados_customer->end[0]->obs ?></textarea>
                                  </div>
                            </div>
                        </div>
                        
                        <div class="modal-footer">
                            <div class="form-row mb-4 mt-3">
                                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Sair sem salvar</button>
                            </div>
                            <!--VALIDAR e SEGUIR-->
                            <div class="form-row mb-4 mt-3">
                                <a id="btn_salvar_end_1" name="btn_salvar_end_1" class="btn btn-outline-success" href="#" role="button">Salvar</a>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        
        
        
        <!--ENDERECO 2-->
        <div class="modal fade" id="add_address2" data-keyboard="false" >
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document" >
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Adicionar endereço 2</h5>
                    </div>
                    <div class="modal-body">
                        
                        <!--ID-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                    <label for="inputState">Identificador</label>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">ID</span>
                                        </div>
                                        <input type="text" class="form-control" id="txt_id_end2" name="txt_id_end2" disabled value="<?php echo $this->view->dados_customer->end[1]->id_address ?>" placeholder="" aria-label="Telefone" aria-describedby="basic-addon1" maxlength="14">
                                    </div>
                            </div>
                        </div>
                        
                        <!--Tipo-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Tipo de Endereço</span>
                                    </div>
                                    <input type="text" class="form-control" id="tipo2" name="tipo2" value="<?php echo $this->view->dados_customer->end[1]->local ?>" aria-label="tipo" aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                        </div>

                        <!--Cep-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Cep</span>
                                    </div>
                                    <input type="text" class="form-control" id="cep2" name="cep2" value="<?php echo $this->view->dados_customer->end[1]->cep ?>" aria-label="CEP"  onblur="pesquisacep2(this.value);"  aria-describedby="basic-addon1">
                                </div>
                            </div>
                        </div>
                        
                        <!--Rua-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Rua</span>
                                    </div>
                                    <input type="text" class="form-control" id="rua2" name="rua2" value="<?php echo $this->view->dados_customer->end[1]->rua ?>" aria-label="CEP"   aria-describedby="basic-addon1" maxlength="255">
                                </div>
                            </div>
                        </div>
                        
                        <!--Numero Bairro-->
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Número e complemento</span>
                                    </div>
                                    <input type="text" class="form-control" id="numero2" name="numero2" value="<?php echo $this->view->dados_customer->end[1]->numero_complemento ?>" aria-label="numero"   aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Bairro</span>
                                    </div>
                                    <input type="text" class="form-control" id="bairro2" name="bairro2" value="<?php echo $this->view->dados_customer->end[1]->bairro ?>" aria-label="Bairro"   aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                        </div>
                        
                        <!--Cidade Estado-->
                        <div class="form-row">
                            <div class="form-group col-md-8">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Cidade</span>
                                    </div>
                                    <input type="text" class="form-control" id="cidade2" name="cidade2" value="<?php echo $this->view->dados_customer->end[1]->cidade ?>" aria-label="numero"   aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Estado</span>
                                    </div>
                                    <input type="text" class="form-control" id="uf2" name="uf2" value="<?php echo $this->view->dados_customer->end[1]->estado ?>" aria-label="numero"   aria-describedby="basic-addon1" maxlength="2">
                                </div>
                            </div>
                        </div>
                       
                        <!--Ponto de referentia-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Ponto de referência</span>
                                    </div>
                                    <input type="text" class="form-control" id="referencia2" name="referencia2" value="<?php echo $this->view->dados_customer->end[1]->referencia ?>" aria-label="numero"   aria-describedby="basic-addon1" maxlength="60">
                                </div>
                            </div>
                        </div>
                        
                        <!--Observacoes-->
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                    <div class="form-group">
                                    <label for="exampleFormControlTextarea1">Observações</label>
                                    <textarea class="form-control" id="txt_obs_endereco_2" rows="3" maxlength="60"><?php echo $this->view->dados_customer->end[1]->obs ?></textarea>
                                  </div>
                            </div>
                        </div>
                        
                        <div class="modal-footer">
                            <div class="form-row mb-4 mt-3">
                                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Sair sem salvar</button>
                            </div>
                            <!--VALIDAR e SEGUIR-->
                            <div class="form-row mb-4 mt-3">
                                <a id="btn_salvar_end_2" name="btn_salvar_end_2" class="btn btn-outline-success" href="#" role="button">Salvar</a>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        
        
        <hr>
        
        
        <div class="esconder" role="alert" id="msg_questao_repetida">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <p><i class="glyphicon glyphicon-alert"></i> Esta questão já existe em nosso banco de dados. Por favor, insira outra.</p>
        </div>
        
        
        <!--VALIDAR e SEGUIR-->
        <div class="form-row mb-4 mt-3">
            <a id="btn_validar" name="btn_validar" class="btn btn-outline-success btn-lg btn-block" href="#" role="button">Salvar</a>
        </div>
    </div>
    
    
    
</div>





<!--form salvar-->
    <form action="/salva_editar_cliente" method="POST" id="edit_cliente">
        
        <input type='hidden'    name="id_customer"                  id="id_customer" value="<?= $this->view->dados_customer->id_customer ?>">
        <input type='hidden'    name="active"                       id="active" value="<?= $this->view->dados_customer->active ?>">
        <input type='hidden'    name="phone_1"                      id="phone_1">
        <input type='hidden'    name="phone_2"                      id="phone_2">
        <input type='hidden'    name="nome"                         id="nome">
        <input type='hidden'    name="cpf"                          id="cpf">
        <input type='hidden'    name="obs"                          id="obs">
        
        <!--endereco1-->
        <input type='hidden'    name="id_dress_1"                   id="id_dress_1" value="<?php echo $this->view->dados_customer->end[0]->id_address ?>">
        <input type='hidden'    name="address_tipo1"                id="address_tipo1">
        <input type='hidden'    name="address_cep1"                 id="address_cep1">
        <input type='hidden'    name="address_rua1"                 id="address_rua1">
        <input type='hidden'    name="address_numero1"              id="address_numero1">
        <input type='hidden'    name="address_bairro1"              id="address_bairro1">
        <input type='hidden'    name="address_cidade1"              id="address_cidade1">
        <input type='hidden'    name="address_estado1"              id="address_estado1">
        <input type='hidden'    name="address_referencia1"          id="address_referencia1">
        <input type='hidden'    name="address_obs1"                 id="address_obs1">
        
        <!--endereco2-->
        <input type='hidden'    name="id_dress_2"                   id="id_dress_2" value="<?php echo $this->view->dados_customer->end[1]->id_address ?>">
        <input type='hidden'    name="address_tipo2"                id="address_tipo2">
        <input type='hidden'    name="address_cep2"                 id="address_cep2">
        <input type='hidden'    name="address_rua2"                 id="address_rua2">
        <input type='hidden'    name="address_numero2"              id="address_numero2">
        <input type='hidden'    name="address_bairro2"              id="address_bairro2">
        <input type='hidden'    name="address_cidade2"              id="address_cidade2">
        <input type='hidden'    name="address_estado2"              id="address_estado2">
        <input type='hidden'    name="address_referencia2"          id="address_referencia2">
        <input type='hidden'    name="address_obs2"                 id="address_obs2">
        
    </form>
















