<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Novo pedido -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >PEDIDO <?= $this->view->id_pedido ?></h3>
            <hr>
    </div>
    
    <!--Alerts-->
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
    <div class="container">
        
        <?php
            if($this->view->dados_pedido->resultado[0]->active == 0){
                ?>
                    <div class="alert alert-danger" role="alert">
                        PEDIDO CANCELADO
                    </div>
                <?PHP
            }
        ?>
        
        
        <!--CABECALHO Dados Iniciais-->
        <div class="form-row" >
                <!--Canto Esquerdo-->
                <div class="form-group col-md-6 rounded p-3" style="background: #EFEFEF">
                    <dl class="row">
                        
                        <dt class="col-sm-3">Data Pedido</dt>
                        <dd class="col-sm-9">
                            <?php echo isset($this->view->dados_pedido->resultado[0]->created_at) ? (new DateTime( $this->view->dados_pedido->resultado[0]->created_at))->format('d/m/Y H:i') : ""?>
                        </dd>

                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                        <dt class="col-sm-3">Nome Cliente</dt>
                        <dd class="col-sm-9">
                            <?php echo isset($this->view->dados_pedido->resultado[0]->name) ? $this->view->dados_pedido->resultado[0]->name : ""?>
                        </dd>

                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                        <dt class="col-sm-3">Entrega</dt>
                        <dd class="col-sm-9">
                            <?php 
                                if ($this->view->endereco_entrega->erro == false){
                                    echo "<p>Local: " . $this->view->endereco_entrega->resultado[0]->local  . "</p>" .
                                                        $this->view->endereco_entrega->resultado[0]->rua . ", " . 
                                                        $this->view->endereco_entrega->resultado[0]->numero_complemento . " - " .
                                                        $this->view->endereco_entrega->resultado[0]->bairro . " - " . 
                                                        $this->view->endereco_entrega->resultado[0]->cidade . " - " . 
                                                        $this->view->endereco_entrega->resultado[0]->estado . " - ". 
                                                        $this->view->endereco_entrega->resultado[0]->cep . "</p>". 
                                         "<p>Referência: " . $this->view->endereco_entrega->resultado[0]->referencia . "</p>";
                                         "<p>Obs: " . $this->view->endereco_entrega->resultado[0]->obs . "</p>";
                                }
                            ?>
                        </dd>
                    </dl>
                </div>
                
                
                <!--Canto Direito-->
                <div class="form-group col-md-6 rounded shadow-sm  p-3 rounded" style="background: #F9F9F9">
                    <dl class="row">
                        
                        <!--PAGO-->
                        <dt class="col-sm-4 float-left">Pago <span class="" role="status" id="loading_pago" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8  text-right">
                            <a class="<?php echo $this->view->dados_pedido->resultado[0]->payment_status == 1 ? "btn btn-success text-white" : "btn btn-outline-success"?>" id="btn_pago_sim" role="button">SIM</a>
                            <a class="<?php echo $this->view->dados_pedido->resultado[0]->payment_status == 0 ? "btn btn-danger text-white" : "btn btn-outline-danger"?>" id="btn_pago_nao" role="button">NÃO</a>
                        </dd>
                        
                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                         <!--Entrega Agendamento-->
                        <dt class="col-sm-4 float-left">Entrega Agendada <span class="" role="status" id="loading_delivery" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8  text-right">
                            <a class="<?php echo $this->view->dados_pedido->resultado[0]->schedule_delivery == 1 ? "btn btn-success text-white" : "btn btn-outline-success"?>" id="btn_entrega_sim" role="button">SIM</a>
                            <a class="<?php echo $this->view->dados_pedido->resultado[0]->schedule_delivery == 0 ? "btn btn-danger text-white" : "btn btn-outline-danger"?>" id="btn_entrega_nao" role="button">NÃO</a>
                        </dd>
                        <dd class="col-sm-12  text-right">
                            <div id="div_data_delivery" class="<?php echo $this->view->dados_pedido->resultado[0]->schedule_delivery == 1 ? "" : "esconder"?>">
                                <div class="col-sm-12 col-xs-12">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">
                                                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                                                &nbsp;&nbsp;Data Entrega&nbsp;
                                                <span class="" role="status" id="loading_data_delivery" aria-hidden="true">
                                            </span>
                                        </div>
                                        <input class="form-control" id="txt_data_delivery" name="date" placeholder="DD/MM/YYYY" type="text" value="<?php echo $this->view->data_entrega?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-xs-12">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">
                                                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                                &nbsp;&nbsp;Horário Entrega&nbsp;
                                                <span class="" role="status" id="loading_hora_delivery" aria-hidden="true">
                                            </span>
                                        </div>
                                        <input class="form-control" id="txt_hora_delivery" name="txt_hora_delivery" placeholder="" type="text" value="<?php echo $this->view->horario_entrega?>" />
                                    </div>
                                </div>
                            </div>
                        </dd>
                        
                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                        <!--STATUS PEDIDO-->
                        <dt class="col-sm-4">Status Pedido <span class="" id="loading_status_pedido" role="status" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8">
                            <select id="select_status_pedido" name="select_status_pedido" class="selectpicker form-control" data-live-search="true" data-header="Escolha uma opção" data-style="btn-outline-dark">
                                <?php
                                    if (isset($this->view->status->resultado)){ 
                                ?>
                                        <option value="0" selected></option>
                                <?php 
                                        foreach ($this->view->status->resultado as $key => $value){ 
                                ?>
                                             <option value="<?php echo $value->id_status ?>" 
                                                     
                                                     > <?php echo $value->id_status . " - " .$value->status?> </option>
                                <?php   }       
                                    }else{
                                ?>
                                        <option value="" selected>Não há valores para mostrar.</option>
                                <?php
                                    }
                                ?>
                            </select>
                            <div class="text-right">
                                <a class="btn btn-outline-info" id="btn_historico_status" role="button">Histórico <span class="" id="loading_historico_status" role="status" aria-hidden="true"></span></a>
                            </div>
                        </dd>
                      
                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                        <!--OBS-->
                        <dt class="col-sm-4">Observações <span class="" role="status" id="loading_obs" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8 text-right">
                            <textarea class="form-control" id="txt_obs_customer" rows="3" maxlength="255"><?php echo $this->view->dados_pedido->resultado[0]->obs  ?></textarea>
                            <a class="btn btn-outline-success disabled mt-1" id="btn_salvar_obs" role="button">Salvo </a>
                        </dd>
                        
                    </dl>
                </div>
                
        </div>
        
        
        <hr>
        <!--Totais-->
        <div class="form-row shadow rounded p-3" style="background: #F9F9F9" >
            
                <dt class="col-sm-12 text-center">
                    <h3>
                            Totais
                            <span class="" id="loading_totais" role="status" aria-hidden="true"></span>    
                    </h3>
                </dt>
                <dt class="col-sm-12 text-center"><hr></dt>
            
                <!--Canto Esquerdo-->
                <div class="form-group col-md-6 ">
                    <dl class="row">
                        
                        <!--ITENS-->
                        <dt class="col-sm-6 float-left"><h4>Total Itens</h4></dt>
                        <dd class="col-sm-6 "> <h4 id="txt_total_itens">0</h4> </dd>

                    </dl>
                </div>
                
                
                <!--Canto Direito-->
                <div class="form-group col-md-6" >
                    <dl class="row">
                        
                        <!--VALOR TOTAL-->
                        <dt class="col-sm-6 float-left"><h4>Valor Total</h4></dt>
                        <dd class="col-sm-6 ">  <h4 id="txt_valor_total">R$0,00</h4> </dd>
                        
                    </dl>
                </div>
                
                <dt class="col-sm-12 text-center"><hr></dt>
                
                <!--Canto Esquerdo-->
                <div class="form-group col-md-6 ">
                    <dl class="row">
                        
                       

                    </dl>
                </div>
                
                
                <!--Canto Direito-->
                <div class="form-group col-md-6" >
                    <dl class="row">
                        
                        <!--FORMA DE PAGAMENTO-->
                        <dt class="col-sm-4">Forma Pagamento <span class="" id="loading_forma_pagamento" role="status" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8">
                            <select id="select_forma_pagamento" name="select_forma_pagamento" class="selectpicker form-control" data-live-search="true" data-header="Escolha uma opção" data-style="btn-outline-dark">
                                <?php
                                    if (isset($this->view->formas_de_pagamento->resultado)){ 
                                ?>
                                        <option value="0" selected></option>
                                <?php 
                                        foreach ($this->view->formas_de_pagamento->resultado as $key => $value){
                                ?>
                                             <option value="<?php echo $value->id_payment_term ?>"
                                                     
                                                     > <?php echo $value->name?> </option>
                                <?php   }       
                                    }else{
                                ?>
                                        <option value="" selected>Não há valores para mostrar.</option>
                                <?php
                                    }
                                ?>
                            </select>
                        </dd>
                        
                    </dl>
                </div>
                
                
                
                
        </div>
        
        
        <div class="mt-5 text-right">
            <a class="btn btn-info text-white" id="btn_add_produto" role="button">Adicionar Produto</a>
        </div>
        
        <!--TABELA PRODUTOS-->
        <div class="mt-1">
            <table class="table table-hover" id="table_produtos">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">ID</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Unit</th>
                        <th scope="col">QTD</th>
                        <th scope="col">Total</th>
                        <th scope="col">OBS</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>@mdo</td>
                        <td><a class="btn btn-outline-danger" id="btn_pago_sim" role="button">Retirar</a></td>
                    </tr>
                </tbody>
            </table>

            <hr>
        </div>
        
        
        

        
        <br><br><br>
   
        <dl class="row ">
                        
            <dt class="col-sm-9"><div class=""  role="status"></div></dt>
            <dd class="col-sm-3">
                <a class="btn btn-danger  btn-block text-white" id="btn_cancelar_pedido" role="button">CANCELAR PEDIDO</a>
                <hr>
            </dd>

        </dl>
        
        
        
        
    </div>
<!--FIM DIV PRINCIPAL-->
</div>



<!--form Armazenando dados-->
<form action="/gerir_pedido" method="POST" id="form_gerir_pedido" class="esconder">
    <input type='text'    name="id_adm"                         id="id_adm"             value="<?php echo $this->view->id_adm ?>">
    <input type='text'    name="id_pedido"                      id="id_pedido"          value="<?= $this->view->dados_pedido->resultado[0]->id_order?>">
    <input type='text'    name="id_status_pedido"               id="id_status_pedido"   value="<?= $this->view->dados_pedido->resultado[0]->fk_id_payment_term?>">
    <input type='text'    name="fk_id_status"                   id="fk_id_status"       value="<?= $this->view->dados_pedido->resultado[0]->fk_id_status?>">
    <input type='text'    name="created_at"                     id="created_at"         value="<?= $this->view->dados_pedido->resultado[0]->created_at?>">
    <input type='text'    name="txt_delivery_status"            id="txt_delivery_status">
</form>





<!--CANCELAR PEDIDO-->
<div class="modal fade bd-example-modal" tabindex="-1" role="dialog" id="modal_cancelar_pedido" >
    <div class="modal-dialog modal modal-dialog-centered" role="document">
        <div class="modal-content">
            
            <div class="modal-header">
                <h5 class="modal-title">CANCELAR PEDIDO</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                
                <div class="container">
                    <div class="row">
                        <div class="col-sm">
                            Deseja cancelar o pedido?
                        </div>
                    </div>
                    <div class="row mt-2">    
                        <div class="col-sm">
                            <div class="alert alert-danger" role="alert">
                                Esta operação não pode ser desfeita.
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            
            <div class="modal-footer text-center">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="btn_cancela_cancelar_pedido">Cancelar</button>
                <button type="button" class="btn btn-danger" id="btn_confirma_cancelar_pedido">
                    <span class="" role="status" aria-hidden="true" id="spinner_cancela_pedido"></span> CANCELAR PEDIDO</button>
            </div>
        </div>
    </div>
</div>


<!--CANCELAR PEDIDO-->
<div class="modal fade bd-example-modal" tabindex="-1" role="dialog" id="modal_cancelando_pedido" data-backdrop="static">
    <div class="modal-dialog modal modal-dialog-centered" role="document">
        <div class="modal-content">
            
            <div class="modal-header">
                <h5 class="modal-title">CANCELANDO PEDIDO</h5>
            </div>
            
            <div class="modal-body">
                
                <div class="container">
                    <div class="row mt-2">    
                        <div class="col-sm">
                            <div class="alert alert-info" role="alert">
                                O pedido está sendo cancelado. <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" ></span>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>


<!--form Armazenando dados-->
<form action="/apagar_pedido" method="POST" id="form_apagar_pedido" class="esconder">
    <input type='text'    name="id_pedido_del"                      id="id_pedido_del"          value="<?= $this->view->dados_pedido->resultado[0]->id_order?>">
</form>











<!-- Modal Historico Status -->
<div class="modal fade bd-example-modal-lg" id="modal_hostorico_status" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            
            <div class="modal-header">
                <h5 class="modal-title" id="TituloModalCentralizado">Histórico de alterações de Status</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            
            <div class="modal-body" id="div_body_historico_status">
                
                <table class="table table-hover" id="table_historico_status">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Item</th>
                            <th scope="col">Usuário</th>
                            <th scope="col">Ordem</th>
                            <th scope="col">status</th>
                            <th scope="col">data</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>











<!--CARDAPIO ATIVO-->
<div class="modal fade bd-example-modal-xl" id="modal_cardapio" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
<div class="modal-dialog modal-xl">
    <div class="modal-content">
        
        <div class="modal-header">
                <h4 class="modal-title" id="TituloModalCentralizado">Cardápio</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                </button>
        </div>
		
            <!-- CONTEUDO MODAL-->
            <div class="modal-body">
		
		<!-- Link Menu Categoria-->
		<h5>Categorias</h5>
		<div class="btn-group-vertical">
                    <?php
                        if(isset($this->view->categorias)){
                            foreach ($this->view->categorias->resultado as $key => $value){
                    ?>
                                <a type="button" href="#cat_<?= $value->id_category?>" class="btn btn-secondary"><?php echo $value->description ?></a>
                    <?php   }
                        }
                    ?>
		</div>
		
		<hr>
		
                
                
                <?php
                    if($this->view->produtos->erro == false){
                        for ($i = 0; $i < sizeof($this->view->categorias->resultado); $i++){
                    ?>
                            <div class="alert alert-primary text-center" role="alert" id="cat_<?= $this->view->categorias->resultado[$i]->id_category ?>">
                                <h3> <?= $this->view->categorias->resultado[$i]->description ?></h3>
                            </div>
                
                
                            <table class="table table-hover">
                                <tbody>
                                    
                                    <?php
                                        for ($j = 0; $j < sizeof($this->view->produtos->resultado); $j++){
                                            if($this->view->produtos->resultado[$j]->fk_id_category == $this->view->categorias->resultado[$i]->id_category){
                                            ?>
                                            <tr>
                                                <td>
                                                    <div class="row">
                                                            <div class="col-3">
                                                                <img id='img-upload' name='img-upload' 
                                                                    <?php echo $this->view->produtos->resultado[$j]->picture_thumb != "0" ? 
                                                                        'src="data:image/jpg;base64,' . $this->view->produtos->resultado[$j]->picture_thumb  . 
                                                                        '"' : "" ; ?>  width="90px"/>
                                                                <input type="hidden"  
                                                                       id="pd_im_<?=$this->view->produtos->resultado[$j]->id_product?>" 
                                                                       value="<?=$this->view->produtos->resultado[$j]->picture_thumb?>">
                                                            </div>
                                                            <div class="col-8">
                                                                    <strong id="pd_tt_<?=$this->view->produtos->resultado[$j]->id_product?>"><?=$this->view->produtos->resultado[$j]->id_product . " - " . $this->view->produtos->resultado[$j]->name ?></strong> <br>
                                                                    <?=$this->view->produtos->resultado[$j]->description?><br>
                                                                    de  
                                                                    <i>R$ <?=$this->view->produtos->resultado[$j]->price_old?></i> 
                                                                    por 
                                                                    <strong>R$ </strong><strong id="pd_pc_<?=$this->view->produtos->resultado[$j]->id_product?>"><?=$this->view->produtos->resultado[$j]->price_new?></strong>
                                                                    <div class="text-right"> <a 
                                                                            onclick="AddProduto(<?=$this->view->produtos->resultado[$j]->id_product?>)"
                                                                            class="btn btn-primary stretched-link"></a> </div>
                                                            </div>
                                                    </div>
                                                </td>
                                              </tr>


                                        <?php  }// fim IF produto igual categoria rodando
                                        }//fim FOR percorrendo produtos
                                    ?>
                                    
                                </tbody>
                              </table>
                
    
                    <?php   }// fim for percorrendo as categorias
                        }else{ // IF produto->erro
                            echo "Cardádio Vazio";
                        }
                ?>
		</div>
		  <!--Fim corpo modal-->

		<div class="modal-footer">
			<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
		</div>
    </div>
</div>
</div>





<!--Confirma ADD produto-->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="modal_confirma_add_produto">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            
            <div class="modal-header">
                <h5 class="modal-title">Incluir Produto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                
                <div class="container">
                    <div class="row">
                        <div class="col-sm">
                            <input type='hidden'    name="txt_add_id"   id="txt_add_id">
                            <img  name='txt_add_img' id="txt_add_img" width="90px" />
                        </div>
                        <div class="col-sm">
                            <p id="txt_add_descricao"></p>
                        </div>
                        <div class="col-sm">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">QTD</span>
                                </div>
                                <input type="number" class="form-control" id="txt_add_qtd"  aria-describedby="basic-addon1" value="1">
                            </div>
                        </div>
                        <div class="col-sm">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">R$</span>
                                </div>
                                <input type="text" class="form-control" id="txt_add_preco"  aria-describedby="basic-addon1">
                            </div>
                        </div>
                    </div>
                    <div class="row mt-2">    
                        <div class="col-sm">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">OBS</span>
                                </div>
                                <textarea class="form-control" id="txt_add_obs" rows="3"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="btn_cancel_add_produto">Cancelar</button>
                <button type="button" class="btn btn-primary" id="btn_incluir_produto">
                    <span class="" role="status" aria-hidden="true" id="spinner_add_produto_pedido"></span> Incluir Produto</button>
            </div>
        </div>
    </div>
</div>
















		