<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Novo pedido -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >PEDIDO <?= $this->view->id_pedido ?></h3>
            <hr>
    </div>
    
    <!--Alerts-->
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
    <div class="container">
        
        
        <!--CABECALHO Dados Iniciais-->
        <div class="form-row" >
                <!--Canto Esquerdo-->
                <div class="form-group col-md-6 rounded p-3" style="background: #EFEFEF">
                    <dl class="row">
                        
                        <dt class="col-sm-3">Data Pedido</dt>
                        <dd class="col-sm-9">
                            <?php echo isset($this->view->dados_pedido->resultado[0]->created_at) ? (new DateTime( $this->view->dados_pedido->resultado[0]->created_at))->format('d/m/Y H:i') : ""?>
                        </dd>

                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                        <dt class="col-sm-3">Nome Cliente</dt>
                        <dd class="col-sm-9">
                            <?php echo isset($this->view->dados_pedido->resultado[0]->name) ? $this->view->dados_pedido->resultado[0]->name : ""?>
                        </dd>

                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                        <dt class="col-sm-3">Entrega</dt>
                        <dd class="col-sm-9">
                            <?php 
                                if ($this->view->endereco_entrega->erro == false){
                                    echo "<p>Local: " . $this->view->endereco_entrega->resultado[0]->local  . "</p>" .
                                                        $this->view->endereco_entrega->resultado[0]->rua . ", " . 
                                                        $this->view->endereco_entrega->resultado[0]->numero_complemento . " - " .
                                                        $this->view->endereco_entrega->resultado[0]->bairro . " - " . 
                                                        $this->view->endereco_entrega->resultado[0]->cidade . " - " . 
                                                        $this->view->endereco_entrega->resultado[0]->estado . " - ". 
                                                        $this->view->endereco_entrega->resultado[0]->cep . "</p>". 
                                         "<p>Referência: " . $this->view->endereco_entrega->resultado[0]->referencia . "</p>";
                                         "<p>Obs: " . $this->view->endereco_entrega->resultado[0]->obs . "</p>";
                                }
                            ?>
                        </dd>
                    </dl>
                </div>
                
                
                <!--Canto Direito-->
                <div class="form-group col-md-6 rounded shadow-sm  p-3 rounded" style="background: #F9F9F9">
                    <dl class="row">
                        
                        <!--PAGO-->
                        <dt class="col-sm-4 float-left">Pago <span class="" role="status" id="loading_pago" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8  text-right">
                            <a class="<?php echo $this->view->dados_pedido->resultado[0]->payment_status == 1 ? "btn btn-success text-white" : "btn btn-outline-success"?>" id="btn_pago_sim" role="button">SIM</a>
                            <a class="<?php echo $this->view->dados_pedido->resultado[0]->payment_status == 0 ? "btn btn-danger text-white" : "btn btn-outline-danger"?>" id="btn_pago_nao" role="button">NÃO</a>
                        </dd>
                        
                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                        <!--FORMA DE PAGAMENTO-->
                        <dt class="col-sm-4">Status Pedido <span class="" id="loading_status_pedido" role="status" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8">
                            <select id="select_status_pedido" name="select_status_pedido" class="selectpicker form-control" data-live-search="true" data-header="Escolha uma opção" data-style="btn-outline-dark">
                                <?php
                                    if (isset($this->view->formas_de_pagamento->resultado)){ 
                                ?>
                                        <option value="0" selected></option>
                                <?php 
                                        foreach ($this->view->formas_de_pagamento->resultado as $key => $value){ 
                                ?>
                                             <option value="<?php echo $value->id_payment_term ?>"> <?php echo $value->name?> </option>
                                <?php   }       
                                    }else{
                                ?>
                                        <option value="" selected>Não há valores para mostrar.</option>
                                <?php
                                    }
                                ?>
                            </select>
                        </dd>
                      
                        <dt class="col-sm-12 text-center"><hr></dt>
                        
                        <!--OBS-->
                        <dt class="col-sm-4">Observações <span class="" role="status" id="loading_obs" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8 text-right">
                            <textarea class="form-control" id="txt_obs_customer" rows="3" maxlength="255"><?php echo $this->view->dados_pedido->resultado[0]->obs  ?></textarea>
                            <a class="btn btn-outline-success disabled mt-1" id="btn_salvar_obs" role="button">Salvo </a>
                        </dd>
                        
                    </dl>
                </div>
                
        </div>
        
        
        <hr>
        <!--Totais-->
        <div class="form-row shadow rounded p-3" style="background: #F9F9F9" >
            
                <dt class="col-sm-12 text-center">
                    <h3>
                            Totais
                            <span class="" id="loading_totais" role="status" aria-hidden="true"></span>    
                    </h3>
                </dt>
                <dt class="col-sm-12 text-center"><hr></dt>
            
                <!--Canto Esquerdo-->
                <div class="form-group col-md-6 ">
                    <dl class="row">
                        
                        <!--ITENS-->
                        <dt class="col-sm-6 float-left"><h4>Total Itens</h4></dt>
                        <dd class="col-sm-6 "> <h4 id="txt_total_itens">0</h4> </dd>

                    </dl>
                </div>
                
                
                <!--Canto Direito-->
                <div class="form-group col-md-6" >
                    <dl class="row">
                        
                        <!--VALOR TOTAL-->
                        <dt class="col-sm-6 float-left"><h4>Valor Total</h4></dt>
                        <dd class="col-sm-6 ">  <h4 id="txt_valor_total">R$0,00</h4> </dd>
                        
                    </dl>
                </div>
                
                <dt class="col-sm-12 text-center"><hr></dt>
                
                <!--Canto Esquerdo-->
                <div class="form-group col-md-6 ">
                    <dl class="row">
                        
                       

                    </dl>
                </div>
                
                
                <!--Canto Direito-->
                <div class="form-group col-md-6" >
                    <dl class="row">
                        
                        <!--FORMA DE PAGAMENTO-->
                        <dt class="col-sm-4">Forma Pagamento <span class="" id="loading_forma_pagamento" role="status" aria-hidden="true"></span></dt>
                        <dd class="col-sm-8">
                            <select id="select_forma_pagamento" name="select_status_pedido" class="selectpicker form-control" data-live-search="true" data-header="Escolha uma opção" data-style="btn-outline-dark">
                                <?php
                                    if (isset($this->view->formas_de_pagamento->resultado)){ 
                                ?>
                                        <option value="0" selected></option>
                                <?php 
                                        foreach ($this->view->formas_de_pagamento->resultado as $key => $value){ 
                                ?>
                                             <option value="<?php echo $value->id_payment_term ?>"> <?php echo $value->name?> </option>
                                <?php   }       
                                    }else{
                                ?>
                                        <option value="" selected>Não há valores para mostrar.</option>
                                <?php
                                    }
                                ?>
                            </select>
                        </dd>
                        
                    </dl>
                </div>
                
                
                
                
        </div>
        
        
        <div class="mt-5 text-right">
            <a class="btn btn-info text-white" id="btn_add_produto" role="button">Adicionar Produto</a>
        </div>
        
        <!--TABELA PRODUTOS-->
        <div class="mt-1">
            <table class="table table-hover" id="table_produtos">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">ID</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Unit</th>
                        <th scope="col">QTD</th>
                        <th scope="col">Total</th>
                        <th scope="col">OBS</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>@mdo</td>
                        <td><a class="btn btn-outline-danger" id="btn_pago_sim" role="button">Retirar</a></td>
                    </tr>
                </tbody>
            </table>

            <hr>
        </div>
        
        
        

        
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
   
        <dl class="row">
                        
            <dt class="col-sm-4">CANCELAR PEDIDO <div class="" id="loading_po" role="status"></div></dt>
            <dd class="col-sm-8">
                <a class="btn btn-danger btn-lg btn-block" id="" role="button">CANCELAR</a>
                <hr>
            </dd>

        </dl>
        
        
        
        
    </div>
<!--FIM DIV PRINCIPAL-->




<!--form Armazenando dados-->
<form action="/gerir_pedido" method="POST" id="form_gerir_pedido" class="">
    <input type='text'    name="id_adm"                         id="id_adm" value="<?php echo $this->view->id_adm ?>">
    <input type='text'    name="id_pedido"                      id="id_pedido" value="<?= $this->view->dados_pedido->resultado[0]->id_order?>">
</form>




































		