<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >GESTÃO À VISTA PEDIDOS</h3>
            <hr>
    </div>
    
    <!--Alerts-->
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
    <div class="container">
        
        <!--Cabecalho-->
        <div class="row mb-2">
            <div class="col-sm"></div>
            <div class="col-sm mt-3">
                <div class="row">
                    <div class="col-sm">
                        <a class="btn btn-outline-success btn-block" id="btn_rel_questao" href="/novo_pedido"  role="button" onclick="LaunchLoading();">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp Adicionar Pedido</a>
                    </div>
                </div>
                <hr>
            </div>
        </div>
        
        <!--Titulo Escolha filtros-->
        <div>
            <!--filtro Data-->
            <div  id="filter_data">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp;&nbsp;Data Inicial</span>
                            </div>
                            <input class="form-control" id="txt_data_inicial" name="date" placeholder="DD/MM/YYYY" type="text"/>
                    <div class="invalid-feedback">Digite alguma data.</div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>&nbsp;&nbsp;Taxa Atualização</span>
                            </div>
                            <select class="form-control">
                                <option value="10" selected>10 segundos</option>
                                <option value="30" selected>30 segundos</option>
                                <option value="60" selected>1 minuto</option>
                                <option value="120" selected>2 minutos</option>
                                <option value="300" selected>5 minutos</option>
                                <option value="600" selected>10 minutos</option>
                                <option value="1800" selected>30 minutos</option>
                            </select>
                        </div>
                    </div>
                </div>   
            </div>
            
        </div>

        <hr>
        <h3 id="txt_count_down">Próxima Atualização: 55</h3>
        <hr>
        
        
       
         <!--TABELA PRINCIPAL-->
        <div class="container_light text-left">
            <table class="table  table-hover" id="tabela_principal" name="tabela_principal">
                  <thead class="thead-dark">
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Cliente</th>
                          <th scope="col">Pagamento</th>
                          <th scope="col">Valor</th>
                          <th scope="col">Status</th>
                          <th scope="col">Situação</th>
                          <th scope="col">Data</th>
                          <th scope="col">Acessar</th>
                        </tr>
                    </thead>
                    <tbody >
        <!--                <tr style="transform: rotate(0);">
                            <th scope="row"><a id="lll" onclick="LaunchLoading();" href="/edit_status?id=" class="stretched-link"></a></th>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>-->
                    </tbody>
            </table>
        </div>
     
    </div>
    
</div>
	



<!--add new cliente-->
<form action="/gerir_pedido" method="POST" id="form_edit_pedido" class="esconder">
    <input type='text'    name="id_pedido"                 id="id_pedido">
</form>










		