<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >NOVO ADMINISTRADOR</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
	
    
    <div class="container">
        

        <!--NOME-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Nome</label>
                    <div class="input-group mb-12">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Nome</span>
                        </div>
                        <input type="text" class="form-control" id="txt_name" name="txt_name"  placeholder=""  aria-describedby="basic-addon1" maxlength="60">
                        <div class="invalid-feedback">Nome obrigatório.</div>
                    </div>
            </div>
	</div>
        
        <!--Email-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Email</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Email</span>
                        </div>
                        <input type="text" class="form-control" id="txt_email" name="txt_email"  placeholder=""  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Descrição obrigatório.</div>
                    </div>
            </div>
	</div>
        
        
        
        <!--Observacoes-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Observações</label>
                        <textarea class="form-control" id="txt_obs_customer" rows="3" maxlength="255"></textarea>
                    </div>
            </div>
	</div>
        
        
        <hr>
        
        <!--VALIDAR e SEGUIR-->
        <div class="form-row mb-4 mt-3">
            <a id="btn_validar" name="btn_validar" class="btn btn-outline-success btn-lg btn-block" href="#" role="button">Salvar</a>
        </div>
    </div>
</div>





<!--form salvar-->
    <form action="/cadastrar_novo_adm" method="POST" id="cadastrar_novo_item">
        <input type='hidden'    name="name"                      id="name">
        <input type='hidden'    name="email"                     id="email">
        <input type='hidden'    name="obs"                       id="obs">
    </form>
















