
    <div class="page">
        
      <!-- Page Header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-modern" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static" data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="56px" data-xl-stick-up-offset="56px" data-xxl-stick-up-offset="56px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
            <div class="rd-navbar-inner-outer">
              <div class="rd-navbar-inner">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <!-- RD Navbar Toggle-->
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="/"><img class="brand-logo-dark" src="images/logo-198x66.png" alt="" width="198" height="66"/></a></div>
                </div>
                <div class="rd-navbar-right rd-navbar-nav-wrap">
                  <div class="rd-navbar-aside">
                    <ul class="rd-navbar-contacts-2">
                      <li>
                        <div class="unit unit-spacing-xs">
                          <div class="unit-left"><span class="icon mdi mdi-phone"></span></div>
                          <div class="unit-body"><a class="phone" href="tel:#">+55 27 98164-1870</a></div>
                        </div>
                      </li>
                      <li>
                        <div class="unit unit-spacing-xs">
                          <div class="unit-left"><span class="icon mdi mdi-map-marker"></span></div>
                          <div class="unit-body"><a class="address" href="#">Vila Velha - ES</a></div>
                        </div>
                      </li>
                    </ul>
                    <ul class="list-share-2">
                        <li><a class="icon mdi mdi-instagram" href="https://www.instagram.com/jazzgrillburger/" target="blanck"></a></li>
                      <li><a class="icon mdi mdi-whatsapp" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870" target="blanck"></a></li>
                    </ul>
                  </div>
                  <div class="rd-navbar-main">
                    <!-- RD Navbar Nav-->
                    <ul class="rd-navbar-nav">
                      <li class="rd-nav-item active"><a class="rd-nav-link" href="/">Inicio</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href="#contatos">Contato</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href="/adm">Login</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
      
      <!-- Swiper-->
      <section class="section swiper-container swiper-slider swiper-slider-2 swiper-slider-3" data-loop="true" data-autoplay="5000" data-simulate-touch="false" data-slide-effect="fade">
        <div class="swiper-wrapper text-sm-left">
            <div class="swiper-slide context-dark" data-slide-bg="images/slide-1-1920x753.jpg">
              <div class="swiper-slide-caption section-md">
                <div class="container">
                  <div class="row">
                    <div class="col-sm-9 col-md-8 col-lg-7 col-xl-7 offset-lg-1 offset-xxl-0">
                      <h2 class="oh swiper-title"><span class="d-inline-block" data-caption-animate="slideInUp" data-caption-delay="0">Burgers perfeitos</span></h2>
                      <p class="big swiper-text" data-caption-animate="fadeInLeft" data-caption-delay="300">Experimente o melhor sanduiche da cidade.</p>
                      <a class="button button-lg button-primary button-winona button-shadow-2" href="#" data-caption-animate="fadeInUp" data-caption-delay="300">Veja Abaixo</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="swiper-slide context-dark" data-slide-bg="images/slide-2-1920x753.jpg">
              <div class="swiper-slide-caption section-md">
                <div class="container">
                  <div class="row">
                    <div class="col-sm-8 col-lg-7 offset-lg-1 offset-xxl-0">
                      <h2 class="oh swiper-title"><span class="d-inline-block" data-caption-animate="slideInDown" data-caption-delay="0">Ingredientes de qualidade</span></h2>
                      <p class="big swiper-text" data-caption-animate="fadeInRight" data-caption-delay="300">Usamos ingredientes selecionados de qualidade em nossos produtos.</p>
                      <div class="button-wrap oh">
                      <a class="button button-lg button-primary button-winona button-shadow-2" href="#" data-caption-animate="slideInUp" data-caption-delay="0">Veja abaixo</a></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
          
        <!-- Swiper Pagination-->
        <div class="swiper-pagination" data-bullet-custom="true"></div>
        <!-- Swiper Navigation-->
        <div class="swiper-button-prev">
            <div class="preview">
              <div class="preview__img"></div>
            </div>
            <div class="swiper-button-arrow"></div>
        </div>
        <div class="swiper-button-next">
            <div class="swiper-button-arrow"></div>
            <div class="preview">
                <div class="preview__img"></div>
            </div>
        </div>
      </section>


        <!-- Our Shop-->
        <section class="section section-lg bg-default">
          
            <div class="container">
                <h3 class="oh-desktop"><span class="d-inline-block wow slideInUp">Cardápio</span></h3>
                
                    
                    
                    <?php
                        for ($i = 0; $i < sizeof($this->view->categorias->resultado); $i++){
                    ?>        
                            <hr>
                            <h4 class="oh-desktop">
                                <span class="d-inline-block wow slideInUp">
                                    <?php echo $this->view->categorias->resultado[$i]->description ?>
                                </span>
                            </h4>
                            <div class="row row-lg row-30">
                                
                                <?php
                                    for ($j = 0; $j < sizeof($this->view->produtos->resultado); $j++){
                                        if($this->view->categorias->resultado[$i]->id_category == $this->view->produtos->resultado[$j]->fk_id_category){
                                ?>
                                    
        <!--CONFIGURACOES DO PRODUTO-->                        
        <div class="col-sm-6 col-lg-4 col-xl-3">
            <article class="product wow fadeInLeft" data-wow-delay=".1s">
                <div class="product-figure">
                    <img <?php echo $this->view->produtos->resultado[$j]->picture_thumb != "0" ? 'src="data:image/jpg;base64,' . $this->view->produtos->resultado[$j]->picture_thumb  . '"' : "" ; ?> alt="" width="161" height="162"/>
                </div>
                <div class="product-rating">
                    
                    <?php
                        if($this->view->produtos->resultado[$j]->star == 1){ 
                            ?>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <?php
                        }
                        if($this->view->produtos->resultado[$j]->star == 2){ 
                            ?>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <?php
                        }
                        if($this->view->produtos->resultado[$j]->star == 3){ 
                            ?>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <?php
                        }
                        if($this->view->produtos->resultado[$j]->star == 4){ 
                            ?>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star text-gray-13"></span>
                            <?php
                        }
                        if($this->view->produtos->resultado[$j]->star == 5){ 
                            ?>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <span class="mdi mdi-star"></span>
                            <?php
                        }
                    ?>
                    
                </div>
                <h6 class="product-title"><?php echo $this->view->produtos->resultado[$j]->name ?></h6>
                <hp class="product-title"><i><?php echo $this->view->produtos->resultado[$j]->description ?></i></p6>
                <div class="product-price-wrap">
                    <div class="product-price product-price-old"><?php echo $this->view->produtos->resultado[$j]->price_old ?></div>
                    <div class="product-price"><?php echo $this->view->produtos->resultado[$j]->price_new ?></div>
                </div>
                <div class="product-button">
                    <div class="button-wrap">
                        <a class="button button-xs button-primary button-winona" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870&text=Boa%20noite!%20Eu%20quero%20um%20<?php echo str_replace(" ","%20",$this->view->produtos->resultado[$j]->id_product); ?>%20-%20<?php echo str_replace(" ","%20",$this->view->produtos->resultado[$j]->name); ?>" target="_blank">
                            Peça pelo Whatsapp
                        </a>
                    </div>
                    <div class="button-wrap">
                        <a class="button button-xs button-secondary button-winona" 
                           href="<?php echo $this->view->url ?>/images/product/<?php echo $this->view->produtos->resultado[$j]->id_product?>.jpg" 
                           data-fancybox 
                           data-caption="<p><strong><?php echo $this->view->produtos->resultado[$j]->name ?></strong> - <i><?php echo $this->view->produtos->resultado[$j]->description?></i></p>">
                                Ver detalhes
                        </a>
                    </div>
                </div>
                <span class="product-badge product-badge-new">#<?php echo $this->view->produtos->resultado[$j]->id_product ?></span>
            </article>
        </div>
        <!--FIM CONFIGURACOES DO PRODUTO-->                         
                                
                                        <?php   }     
                                    }
                                ?>
                                
                            </div>
                            
                            
                    <?php        
                        }
                    ?>
                    
       
            </div>
        </section>

       

        <div id="modal01" class="w3-modal" onclick="this.style.display='none'">
            <span class="w3-button w3-hover-red w3-xlarge w3-display-topright">&times;</span>
            <div class="w3-modal-content w3-animate-zoom">
                <img id="img01" style="width:100%">
            </div>
        </div>
        
<script>
    function onClick(element) {
      document.getElementById("img01").src = element.src;
      document.getElementById("modal01").style.display = "block";
    }
</script>
        
        
        
        
        
        

        <!-- What People say-->
        <section class="section section-xl bg-default">
            <div class="container">
              <h3 class="wow fadeInLeft">O que estão dizendo</h3>
            </div>
            <div class="container container-style-1">
                <div class="owl-carousel owl-style-12" data-items="1" data-sm-items="2" data-lg-items="3" data-margin="30" data-xl-margin="45" data-autoplay="true" data-nav="true" data-center="true" data-smart-speed="400">
                
                    <?php
                        for($p = 0; $p < sizeof($this->view->testemunhos->resultado); $p++){
                            ?>
                                <article class="quote-tara">
                                    <div class="quote-tara-caption">
                                        <div class="quote-tara-text">
                                            <p class="q"><?php echo $this->view->testemunhos->resultado[$p]->testimony ?></p>
                                        </div>
                                        <div class="quote-tara-figure">
                                            <img <?php echo $this->view->testemunhos->resultado[$p]->thumb != "0" ? 'src="data:image/jpg;base64,' . $this->view->testemunhos->resultado[$p]->thumb  . '"' : "" ; ?> 
                                                 alt="" width="115" height="115"/>
                                        </div>
                                    </div>
                                    <h6 class="quote-tara-author"><?php echo $this->view->testemunhos->resultado[$p]->name ?></h6>
                                    <div class="quote-tara-status"><?php echo $this->view->testemunhos->resultado[$p]->status ?></div>
                                </article>
                            <?php
                        }
                    ?>
              </div>
            </div>
        </section>

    

   
  
      <!-- Page Footer-->
      <footer class="section footer-modern context-dark footer-modern-2">
        <div class="footer-modern-line">
          <div class="container">
            <div class="row row-50">
              <div class="col-lg-4 col-xl-5">
                <h5 class="footer-modern-title oh-desktop"><span class="d-inline-block wow slideInLeft">Newsletter</span></h5>
                <p class="wow fadeInRight">Assine nosso canal de comunicação para ficar por dentro de todas as novidades.</p>
                
                
                <!-- RD Mailform-->
                <form class="rd-form rd-mailform rd-form-inline rd-form-inline-sm oh-desktop" data-form-output="form-output-global" >
                    <div class="form-wrap wow slideInUp">
                        <input class="form-input" id="subscribe-form-2-email" type="email" name="email" data-constraints="@Email @Required"/>
                        <label class="form-label" for="subscribe-form-2-email">Digite seu E-mail</label>
                    </div>
                    <div class="form-button form-button-2 wow slideInRight">
                        <button class="button button-sm button-icon-3 button-primary button-winona" id="btn_subscribe_email" ><span class="d-none d-xl-inline-block">Cadastrar</span><span class="icon mdi mdi-telegram d-xl-none"></span></button>
                    </div>
                </form>
                
                
                <form class="esconder"  method="post" action="/subscribe">
                    <input class="form-input" id="txt_email" />
                </form>
                
                
              </div>
            </div>
          </div>
        </div>
          
        <div class="footer-modern-line-2">
          <div class="container">
            <div class="row row-30 align-items-center">
                <div class="col-sm-6 col-md-7 col-lg-4 col-xl-4">
                    <div class="row row-30 align-items-center text-lg-center">
                        <div class="col-md-7 col-xl-6"><a class="brand" href="index.html"><img src="images/logo-inverse-198x66.png" alt="" width="198" height="66"/></a></div>
                        <div class="col-md-5 col-xl-6">
                            <!--<div class="iso-1"><span><img src="images/like-icon-58x25.png" alt="" width="58" height="25"/></span><span class="iso-1-big">9.4k</span></div>-->
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-12 col-lg-8 col-xl-8 oh-desktop" id="contatos">
                <a href="#contatos">.</a>
                <div class="group-xmd group-sm-justify">
                    <div class="footer-modern-contacts wow slideInUp">
                        <div class="unit unit-spacing-sm align-items-center">
                            <div class="unit-left"><span class="icon icon-24 mdi mdi-phone"></span></div>
                            <div class="unit-body"><a class="phone" href="tel:#">+55 27 9 8164-1870</a></div>
                        </div>
                    </div>
                  <div class="footer-modern-contacts wow slideInDown">
                    <div class="unit unit-spacing-sm align-items-center">
                      <div class="unit-left"><span class="icon mdi mdi-email"></span></div>
                      <div class="unit-body"><a class="mail" href="mailto:#">jazzgrillburger@gmail.com.br</a></div>
                    </div>
                  </div>
                  <div class="wow slideInRight">
                    <ul class="list-inline footer-social-list footer-social-list-2 footer-social-list-3">
                      <li><a class="icon mdi mdi-instagram" href="https://www.instagram.com/jazzgrillburger/" target="blanck"></a></li>
                      <li><a class="icon mdi mdi-whatsapp" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870" target="blanck"></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="footer-modern-line-3">
          <div class="container">
            <div class="row row-10 justify-content-between">
              <div class="col-md-6"><span>Vila Velha - ES</span></div>
              <div class="col-md-auto">
                <!-- Rights-->
                <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span><span></span><span>.&nbsp;</span><span>All Rights Reserved.</span><span> Design&nbsp;by&nbsp;<a href="#">Paulo Franco</a></span></p>
              </div>
            </div>
          </div>
        </div>
      </footer>
      
      
      
      
      
      
    </div>
    
    
    
    
    
           