<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >NOVA CATEGORIA</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
	
    
    <div class="container">
        


        
        <!--Descricao-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Nome Categoria</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Descrição</span>
                        </div>
                        <input type="text" class="form-control" id="txt_descricao" name="txt_descricao"  placeholder=""  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Descrição obrigatório.</div>
                    </div>
            </div>
	</div>
        
        
        <!--Sequencia-->
        <div class="form-row">
            <div class="form-group col-md-6">
                    <label for="inputState">Sequência</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Ordem</span>
                        </div>
                        <input  type="number" class="form-control" id="txt_ordem" name="txt_ordem"  placeholder=""  aria-describedby="basic-addon1" maxlength="2">
                        <div class="invalid-feedback">Sequência obrigatório.</div>
                    </div>
            </div>
	</div>
        
        <hr>
        
        <!--VALIDAR e SEGUIR-->
        <div class="form-row mb-4 mt-3">
            <a id="btn_validar" name="btn_validar" class="btn btn-outline-success btn-lg btn-block" href="#" role="button">Salvar</a>
        </div>
    </div>
</div>





<!--form salvar-->
    <form action="/cadastrar_nova_categoria" method="POST" id="cadastrar_novo_item">
        
        <input type='hidden'    name="description"               id="description">
        <input type='hidden'    name="sequence"                  id="sequence">
    </form>
















