<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >EDITAR CATEGORIA</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
	
    
    <div class="container">
        
        <!--ID e ATIVO-->
        <div class="row mb-2">
                <div class="col-sm">
                    <!--ID-->
                    <div class="form-row">
                        <div class="form-group col-md-6">
                                <label for="inputState">Identificador</label>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">ID</span>
                                    </div>
                                    <input type="text" class="form-control" id="txt_id" name="txt_id" disabled value="<?php echo $this->view->dados->id_category  ?>" placeholder="" aria-label="Telefone" aria-describedby="basic-addon1" maxlength="14">
                                </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-sm mt-3">
                    <div class="row">&nbsp Categoria Ativa</div>
                    <div class="row">
                            <div class=" col-sm">
                                <a class="<?= $this->view->dados->active == 1 ? "btn btn-success btn-block" : "btn btn-outline-success btn-block"?>" id="ativo_sim" role="button">ATIVO</a>
                            </div>
                            <div class="col-sm">
                                <a class="<?= $this->view->dados->active == 0 ? "btn btn-danger btn-block" : "btn btn-outline-danger btn-block"?>" id="ativo_nao" role="button">INATIVO</a>
                            </div>
                    </div>
                </div>
        </div>


        
        <!--Descricao-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Nome Categoria</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Descrição</span>
                        </div>
                        <input type="text" class="form-control" id="txt_descricao" name="txt_descricao" value="<?php echo $this->view->dados->description  ?>"  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Descrição obrigatório.</div>
                    </div>
            </div>
	</div>
        
        <hr>
        
        <!--VALIDAR e SEGUIR-->
        <div class="form-row mb-4 mt-3">
            <a id="btn_validar" name="btn_validar" class="btn btn-outline-success btn-lg btn-block" href="#" role="button">Salvar</a>
        </div>
    </div>
</div>





<!--form salvar-->
    <form action="/salvar_edit_categoria" method="POST" id="cadastrar_novo_item">
        
        <input type='hidden'    name="id_category"               id="id_category" value="<?php echo $this->view->dados->id_category  ?>">
        <input type='hidden'    name="description"               id="description" >
        <input type='hidden'    name="active"                    id="active" value="<?php echo $this->view->dados->active  ?>">
    </form>
















