<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >NOVO PRODUTO</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
	
    
    <div class="container">
        
        <!--Categoria-->
        <div class="form-row">
            <div class="form-group col-md-6">
                    <label for="inputState">Categoria</label>
                    <select id="select_categoria" name="select_categoria" class="selectpicker form-control" data-live-search="true" data-header="Escolha uma Categoria" data-style="btn-outline-dark">
                        <?php
                            if (isset($this->view->categorias)){ 
                        ?>
                                <option value="0" selected></option>
                        <?php 
                                foreach ($this->view->categorias as $key => $value){ 
                        ?>
                                     <option value="<?php echo $value->id_category ?>"> <?php echo $value->description?> </option>
                        <?php   }       
                            }else{
                        ?>
                                <option value="" selected>Não há valores para mostrar.</option>
                        <?php
                            }
                        ?>
                    </select>
            </div>
            
            <!--Estrelas-->
            <div class="form-group col-md-6" id="radio_grupin">
                <label for="inputState">Estrelas</label><br>
                <div class="form-check form-check-inline" id="radio_btn">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                    <label class="form-check-label" for="inlineRadio1">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                    <label class="form-check-label" for="inlineRadio2">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                    <label class="form-check-label" for="inlineRadio3">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option4">
                    <label class="form-check-label" for="inlineRadio4">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="form-check form-check-inline ">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio5" value="option5">
                    <label class="form-check-label" for="inlineRadio5">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="invalid-feedback">Classificação obrigatória.</div>
            </div>
        </div>

        <!--NOME-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Nome</label>
                    <div class="input-group mb-12">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Nome</span>
                        </div>
                        <input type="text" class="form-control" id="txt_name" name="txt_name"  placeholder=""  aria-describedby="basic-addon1" maxlength="60">
                        <div class="invalid-feedback">Nome obrigatório.</div>
                    </div>
            </div>
	</div>
        
        <!--Descricao-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Descrição Detalhada</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Descrição</span>
                        </div>
                        <input type="text" class="form-control" id="txt_descricao" name="txt_descricao"  placeholder=""  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Descrição obrigatório.</div>
                    </div>
            </div>
	</div>
        
        
        
        <!--Precos-->
        <div class="form-row">
            
            <!--Precopadrao-->
            <div class="form-group col-md-6">
                    <label for="inputState">Valor Padrão</label>
                    <div class="input-group mb-12">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Preço R$</span>
                        </div>
                        <input type="text" class="form-control" id="txt_preco_old" name="txt_preco_old"  placeholder=""  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Preço obrigatório.</div>
                    </div>
            </div>
   
            <!--Preco Atual-->
            <div class="form-group col-md-6">
                    <label for="inputState">Valor Atual</label>
                    <div class="input-group mb-12">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Preço R$</span>
                        </div>
                        <input type="text" class="form-control" id="txt_preco_new" name="txt_preco_new"  placeholder=""  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Preço obrigatório.</div>
                    </div>
            </div>
            
   
	</div>
       
        
        
        
        
        
        <!--Foto-->
        <div class="col-auto">
                <div class="card card-body bg-light" id="card_img_1">

                    <div class="container " id="container_imgagem">
                        <div class="">
                            <div class="">
                                <label>IMAGEM MINIATURA (162 x 162)</label>
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <span class="btn btn-default btn-file">
                                            <input type="file" id="img_select" name="img_select" accept="image/*">
                                        </span>
                                    </span>
                                    <input type="text" class="form-control" id="img_nome" name="img_nome" readonly>
                                </div>
                                <img id='img-upload' name='img-upload'/>
                                    
                            </div>
                            <div class="text-left" style="color: white">
                                <a class="btn btn-danger" role="button" id="btn_limpa_imagem"><span class="glyphicon glyphicon-remove"></span> Limpar imagem</a>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        
        
        
        <br>
        
        <!--Foto-->
        <div class="col-auto">
                <div class="card card-body bg-light" id="card_img_2">

                    <div class="container " id="container_imgagem2">
                        <div class="">
                            <div class="">
                                <label>IMAGEM GRANDE (800 X 800)</label>
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <span class="btn btn-default btn-file">
                                            <input type="file" id="img_select2" name="img_select2" accept="image/*">
                                        </span>
                                    </span>
                                    <input type="text" class="form-control" id="img_nome2" name="img_nome2" readonly>
                                </div>
                                <img id='img-upload2' name='img-upload2'/>
                                    
                            </div>
                            <div class="text-left" style="color: white">
                                <a class="btn btn-danger" role="button" id="btn_limpa_imagem2"><span class="glyphicon glyphicon-remove"></span> Limpar imagem</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
        
        
        
        <hr>
        
        <!--VALIDAR e SEGUIR-->
        <div class="form-row mb-4 mt-3">
            <a id="btn_validar" name="btn_validar" class="btn btn-outline-success btn-lg btn-block" href="#" role="button">Salvar</a>
        </div>
    </div>
</div>





<!--form salvar-->
<form action="/cadastrar_novo_produto" method="POST" id="cadastrar_novo_item" class="esconder" enctype="multipart/form-data">
        
        <input type='hidden'    name="fk_id_category"           id="fk_id_category">
        <input type='hidden'    name="name"                     id="name">
        <input type='hidden'    name="description"              id="description">
        <input type='hidden'    name="star"                     id="star">
        <input type='hidden'    name="price_new"                id="price_new">
        <input type='hidden'    name="price_old"                id="price_old">
        <input type='hidden'    name="picture_thumb"            id="picture_thumb">
        <input type='file'      name="picture_large"            id="picture_large">
        
    </form>
















