<div class="container" style="padding-bottom: 0px">
    
    <!-- Cabecalho Login -->
    <div  style="background-color: #cbcbcb;">
            <hr>
            <h3 class="font-shadow" style="text-align: center;  font-family: Arial Black" >EDITAR PRODUTO</h3>
            <hr>
    </div>
    
    <div class="">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    
	
    
    <div class="container">
        
        
        <!--ID e ATIVO-->
        <div class="row mb-2">
                <div class="col-sm">
                    <!--ID-->
                    <div class="form-row">
                        <div class="form-group col-md-6">
                                <label for="inputState">Identificador</label>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">ID</span>
                                    </div>
                                    <input type="text" class="form-control" id="txt_id" name="txt_id" disabled value="<?php echo $this->view->dados->id_product  ?>" placeholder="" aria-label="Telefone" aria-describedby="basic-addon1" maxlength="14">
                                </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-sm mt-3">
                    <div class="row">&nbsp Item Ativo</div>
                    <div class="row">
                            <div class=" col-sm">
                                <a class="<?= $this->view->dados->active == 1 ? "btn btn-success btn-block" : "btn btn-outline-success btn-block"?>" id="ativo_sim" role="button">ATIVO</a>
                            </div>
                            <div class="col-sm">
                                <a class="<?= $this->view->dados->active == 0 ? "btn btn-danger btn-block" : "btn btn-outline-danger btn-block"?>" id="ativo_nao" role="button">INATIVO</a>
                            </div>
                    </div>
                </div>
        </div>
        
        
        <!--Categoria-->
        <div class="form-row">
            <div class="form-group col-md-6">
                    <label for="inputState">Categoria</label>
                    <select id="select_categoria" name="select_categoria" class="selectpicker form-control" data-live-search="true" data-header="Escolha uma Categoria" data-style="btn-outline-dark">
                        <?php
                            if (isset($this->view->categorias)){ 
                        ?>
                                <option value="0" selected></option>
                        <?php 
                                foreach ($this->view->categorias as $key => $value){ 
                        ?>
                                     <option value="<?php echo $value->id_category ?>" > <?php echo $value->description?> </option>
                        <?php   }       
                            }else{
                        ?>
                                <option value="" selected>Não há valores para mostrar.</option>
                        <?php
                            }
                        ?>
                    </select>
            </div>
            
            <!--Estrelas-->
            <div class="form-group col-md-6" id="radio_grupin">
                <label for="inputState">Estrelas</label><br>
                <div class="form-check form-check-inline" id="radio_btn">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1" <?php echo $this->view->dados->star == 1 ? "checked" : ""  ?>>
                    <label class="form-check-label" for="inlineRadio1">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2" <?php echo $this->view->dados->star == 2 ? "checked" : ""  ?>>
                    <label class="form-check-label" for="inlineRadio2">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3" <?php echo $this->view->dados->star == 3 ? "checked" : ""  ?>>
                    <label class="form-check-label" for="inlineRadio3">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option4" <?php echo $this->view->dados->star == 4 ? "checked" : ""  ?>>
                    <label class="form-check-label" for="inlineRadio4">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="form-check form-check-inline ">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio5" value="option5" <?php echo $this->view->dados->star == 5 ? "checked" : ""  ?>>
                    <label class="form-check-label" for="inlineRadio5">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </label>
                </div>
                <div class="invalid-feedback">Classificação obrigatória.</div>
            </div>
        </div>

        <!--NOME-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Nome</label>
                    <div class="input-group mb-12">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Nome</span>
                        </div>
                        <input type="text" class="form-control" id="txt_name" name="txt_name"  value="<?php echo $this->view->dados->name?>"  aria-describedby="basic-addon1" maxlength="60">
                        <div class="invalid-feedback">Nome obrigatório.</div>
                    </div>
            </div>
	</div>
        
        <!--Descricao-->
        <div class="form-row">
            <div class="form-group col-md-12">
                    <label for="inputState">Descrição Detalhada</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Descrição</span>
                        </div>
                        <input type="text" class="form-control" id="txt_descricao" name="txt_descricao"  value="<?php echo $this->view->dados->description?>"  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Descrição obrigatório.</div>
                    </div>
            </div>
	</div>
        
        
        
        <!--Precos-->
        <div class="form-row">
            
            <!--Precopadrao-->
            <div class="form-group col-md-6">
                    <label for="inputState">Valor Padrão</label>
                    <div class="input-group mb-12">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Preço R$</span>
                        </div>
                        <input type="text" class="form-control" id="txt_preco_old" name="txt_preco_old"  value="<?php echo $this->view->dados->price_old?>"  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Preço obrigatório.</div>
                    </div>
            </div>
   
            <!--Preco Atual-->
            <div class="form-group col-md-6">
                    <label for="inputState">Valor Atual</label>
                    <div class="input-group mb-12">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Preço R$</span>
                        </div>
                        <input type="text" class="form-control" id="txt_preco_new" name="txt_preco_new"  value="<?php echo $this->view->dados->price_new?>"  aria-describedby="basic-addon1" maxlength="255">
                        <div class="invalid-feedback">Preço obrigatório.</div>
                    </div>
            </div>
            
   
	</div>
       
        
        
        
        
        
        <!--Foto Mini-->
        <div class="col-auto">
                <div class="card card-body bg-light" id="card_img_1">
                    
                    <label for="exampleFormControlTextarea1">Imagem Miniatura</label>
                    <p>
                        <button class="btn btn-info" id="btn_insert_img" type="button" data-toggle="collapse" data-target="#collapseImg" aria-expanded="false" aria-controls="collapseImg">
                            Imagem Miniatura
                        </button>
                    </p>
                    <div class="collapse" id="collapseImg">
                    <div class="card card-body">

                    <div class="container " id="container_imgagem">
                        <div class="">
                            <div class="">
                                <label>IMAGEM MINIATURA (162 x 162)</label>
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <span class="btn btn-default btn-file">
                                            <input type="file" id="img_select" name="img_select" accept="image/*">
                                        </span>
                                    </span>
                                    <input type="text" class="form-control" id="img_nome" name="img_nome" readonly>
                                </div>
                                <img id='img-upload' name='img-upload' <?php echo $this->view->dados->picture_thumb != "0" ? 'src="data:image/jpg;base64,' . $this->view->dados->picture_thumb  . '"' : "" ; ?>/>
                                    
                            </div>
                            <div class="text-left" style="color: white">
                                <a class="btn btn-danger" role="button" id="btn_limpa_imagem"><span class="glyphicon glyphicon-remove"></span> Limpar imagem</a>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                </div>
        </div>
        
        
        <br>
        
        <!--Foto-->
        <div class="col-auto">
                <div class="card card-body bg-light" id="card_img_2">
                    
                    <label for="exampleFormControlTextarea1">Foto Produto</label>
                    <p>
                        <button class="btn btn-info" id="btn_insert_img" type="button" data-toggle="collapse" data-target="#collapseImg2" aria-expanded="false" aria-controls="collapseImg">
                            Foto Produto
                        </button>
                    </p>
                    <div class="collapse" id="collapseImg2">
                    <div class="card card-body">

                    <div class="container " id="container_imgagem2">
                        <div class="">
                            <div class="">
                                <label>IMAGEM GRANDE (800 X 800)</label>
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <span class="btn btn-default btn-file">
                                            <input type="file" id="img_select2" name="img_select2" accept="image/*">
                                        </span>
                                    </span>
                                    <input type="text" class="form-control" id="img_nome2" name="img_nome2" readonly>
                                </div>
                                <img id='img-upload2' name='img-upload2' <?php echo $this->view->dados->picture_large != "0" ? 'src="data:image/jpg;base64,' . $this->view->dados->picture_large  . '"' : "" ; ?>/>
                                    
                            </div>
                            <div class="text-left" style="color: white">
                                <a class="btn btn-danger" role="button" id="btn_limpa_imagem2"><span class="glyphicon glyphicon-remove"></span> Limpar imagem</a>
                            </div>
                        </div>
                    </div>
                    </div>
                    </div>
                </div>
        </div>
        
        
        <br>
        
        <!--VALIDAR e SEGUIR-->
        <div class="form-row mb-4 mt-3">
            <a id="btn_validar" name="btn_validar" class="btn btn-outline-success btn-lg btn-block" href="#" role="button">Salvar Produto</a>
        </div>
        
        <br>
    </div>
    
    

    <div class="bg-light">
        <hr>
        <hr>
        <hr>
    </div>
    

    
    <!--ITENS PRODUTO-->
    <div class="container">
        <h2 class="text-center"><u>ITENS DO PRODUTO</u></h2>
        
        
        <div class="form-row">
            <!--ITENS-->
            <div class="form-group col-md-6">
                <label for="inputState">Insira os itens <span class="spinner-border spinner-border-sm" id="loading_item"></span></label>
                    <select id="select_item" name="select_item" disabled class="selectpicker form-control" data-live-search="true" data-header="Escolha um Item" data-style="btn-outline-dark">
                        <option value="0"></option>
                        <?php
                            if (isset($this->view->itens)){ 

                                foreach ($this->view->itens as $key => $value){ 
                        ?>
                                     <option value="<?php echo $value->id_item?>">
                                        <?php echo $value->name?> 
                                     </option>
                        <?php   }       
                            }else{
                        ?>
                                <option value="" selected>Não há valores para mostrar.</option>
                        <?php
                            }
                        ?>
                    </select>
            </div>
            
            <!--Preco Custo-->
            <div class="form-group col-md-6 mt-4">
                <h4 id="txtcusto_total" class="text-right bg-light">Custo total R$ 0,00</h4>
            </div>
        </div>
        
        
        
        
        <div class="container mt-4">

<!--            <button onclick="adicionaLinha('table_itens')">Adicionar</button>-->

            <table class="table table-hover" id="table_itens" name="table_itens">
                <tr>
                        <th scope="col">#</th>
                        <th scope="col">ID</th>
                        <th scope="col">Nome</th>
                        <th scope="col">UN</th>
                        <th scope="col">Custo</th>
                        <th scope="col"></th>
                </tr>
            </table> 
        </div>
        
        
        
        
        
        
        
        
        
        
    </div>
    
    
    
    
    
    
    
</div>





<!--form salvar-->
    <form action="/salva_edit_produto" method="POST" id="salva_edit_produto">
        
        <input type='hidden'    name="id_product"               id="id_product"     value="<?php echo $this->view->dados->id_product  ?>">
        <input type='hidden'    name="fk_id_category"           id="fk_id_category" value="<?php echo $this->view->dados->fk_id_category  ?>">
        <input type='hidden'    name="name"                     id="name">
        <input type='hidden'    name="description"              id="description">
        <input type='hidden'    name="star"                     id="star">
        <input type='hidden'    name="price_new"                id="price_new">
        <input type='hidden'    name="price_old"                id="price_old">
        <input type='hidden'    name="picture_thumb"            id="picture_thumb">
        <input type='hidden'    name="picture_large"            id="picture_large">
        <input type='hidden'    name="active"                   id="active"         value="<?php echo $this->view->dados->active  ?>">
        
    </form>
















