

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="assets/css/login.css">

    <link rel="icon" href="images/favicon.ico">

    <!-- Bootstrap CSS -->
    <link rel="icon" href="images/favicon.ico">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/css/login.css">

    <title>Erro - Jazz Grill</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
    <div class="container">
        <a class="brand" href="/">
            <img class="brand-logo-dark" src="images/logo-198x66.png" alt="" width="198" height="66"/>
        </a>
    </div>
</nav>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Erro 404</div>
                    <div class="card-body">
                        <form action="" method="">
                            <div class="form-group row">
                                <p>O endereço que está tentando acessar não é válido.</p>
                            </div>
                            <div class="form-group row">
                                <p>Por favor, verifique o caminho desejado e tente novamente.</p>
                            </div>
                            
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>

</main>



<!-- Javascript-->
    
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/popper.min.js" crossorigin="anonymous"></script>
    <script src="/assets/js/bootstrap.min.js" crossorigin="anonymous"></script>



</body>
</html>