<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="shortcut icon" href="/images/favicon.ico">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.css">
    <link rel="stylesheet" href="assets/css/fonts.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/jquery.fancybox.min.css">
    
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-176442547-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-176442547-1');
    </script>

    
    
    
    <title><?php echo $this->getPageTitle('|') ?>Jazz Grill</title>
</head>
<body>
    
    <!-- Import do Menu -->
    <?php require_once __DIR__ . "/menu_main.phtml" ?>

    <!-- Import do Conteudo principal -->
    <?php $this->content() ?>

 
    <!-- Optional JavaScript -->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="assets/js/core.min.js"></script>
    <script src="assets/js/script.js"></script>
    <script src="assets/js/jquery.fancybox.min.js"></script>
    <!-- coded by Himic-->
    <script src="assets/js/main_page_script.js"></script>
    
    </body>
</html>