<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="shortcut icon" href="/images/favicon.ico">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.css">
    <link rel="stylesheet" href="assets/css/fonts.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/jquery.fancybox.min.css">
    
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-176442547-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-176442547-1');
    </script>

    
    
    
    <title><?php echo $this->getPageTitle('|') ?>Jazz Grill</title>
</head>
<body>
    
    <!-- Import do Menu -->
    <?php require_once __DIR__ . "/menu_main.phtml" ?>

    <!-- Import do Conteudo principal -->
    <?php $this->content() ?>

    
    
    
    <div class="page">
      <!-- Page Header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-modern" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static" data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="56px" data-xl-stick-up-offset="56px" data-xxl-stick-up-offset="56px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
            <div class="rd-navbar-inner-outer">
              <div class="rd-navbar-inner">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <!-- RD Navbar Toggle-->
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="/"><img class="brand-logo-dark" src="images/logo-198x66.png" alt="" width="198" height="66"/></a></div>
                </div>
                <div class="rd-navbar-right rd-navbar-nav-wrap">
                  <div class="rd-navbar-aside">
                    <ul class="rd-navbar-contacts-2">
                      <li>
                        <div class="unit unit-spacing-xs">
                          <div class="unit-left"><span class="icon mdi mdi-phone"></span></div>
                          <div class="unit-body"><a class="phone" href="tel:#">+55 27 98164-1870</a></div>
                        </div>
                      </li>
                      <li>
                        <div class="unit unit-spacing-xs">
                          <div class="unit-left"><span class="icon mdi mdi-map-marker"></span></div>
                          <div class="unit-body"><a class="address" href="#">Vila Velha - ES</a></div>
                        </div>
                      </li>
                    </ul>
                    <ul class="list-share-2">
                      <li><a class="icon mdi mdi-instagram" href="#"></a></li>
                      <li><a class="icon mdi mdi-whatsapp" href="#"></a></li>
                    </ul>
                  </div>
                  <div class="rd-navbar-main">
                    <!-- RD Navbar Nav-->
                    <ul class="rd-navbar-nav">
                      <li class="rd-nav-item active"><a class="rd-nav-link" href="/">Inicio</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href="#contatos">Contato</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href="/adm">Login</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <!-- Swiper-->
      <section class="section swiper-container swiper-slider swiper-slider-2 swiper-slider-3" data-loop="true" data-autoplay="5000" data-simulate-touch="false" data-slide-effect="fade">
        <div class="swiper-wrapper text-sm-left">
            <div class="swiper-slide context-dark" data-slide-bg="images/slide-1-1920x753.jpg">
              <div class="swiper-slide-caption section-md">
                <div class="container">
                  <div class="row">
                    <div class="col-sm-9 col-md-8 col-lg-7 col-xl-7 offset-lg-1 offset-xxl-0">
                      <h2 class="oh swiper-title"><span class="d-inline-block" data-caption-animate="slideInUp" data-caption-delay="0">Burgers perfeitos</span></h2>
                      <p class="big swiper-text" data-caption-animate="fadeInLeft" data-caption-delay="300">Experimente o melhor sanduiche da cidade.</p>
                      <a class="button button-lg button-primary button-winona button-shadow-2" href="#" data-caption-animate="fadeInUp" data-caption-delay="300">Veja Abaixo</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="swiper-slide context-dark" data-slide-bg="images/slide-2-1920x753.jpg">
              <div class="swiper-slide-caption section-md">
                <div class="container">
                  <div class="row">
                    <div class="col-sm-8 col-lg-7 offset-lg-1 offset-xxl-0">
                      <h2 class="oh swiper-title"><span class="d-inline-block" data-caption-animate="slideInDown" data-caption-delay="0">Ingredientes de qualidade</span></h2>
                      <p class="big swiper-text" data-caption-animate="fadeInRight" data-caption-delay="300">Usamos ingredientes selecionados de qualidade em nossos produtos.</p>
                      <div class="button-wrap oh">
                      <a class="button button-lg button-primary button-winona button-shadow-2" href="#" data-caption-animate="slideInUp" data-caption-delay="0">Veja abaixo</a></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
        <!-- Swiper Pagination-->
        <div class="swiper-pagination" data-bullet-custom="true"></div>
        <!-- Swiper Navigation-->
        <div class="swiper-button-prev">
            <div class="preview">
              <div class="preview__img"></div>
            </div>
            <div class="swiper-button-arrow"></div>
        </div>
        <div class="swiper-button-next">
            <div class="swiper-button-arrow"></div>
            <div class="preview">
                <div class="preview__img"></div>
            </div>
        </div>
      </section>


        <!-- Our Shop-->
        <section class="section section-lg bg-default">
          
            <div class="container">
                <h3 class="oh-desktop"><span class="d-inline-block wow slideInUp">Cardápio</span></h3>
                <div class="row row-lg row-30">
                    
                    <div class="col-sm-6 col-lg-4 col-xl-3">
                        <!-- Product-->
                        <article class="product wow fadeInLeft" data-wow-delay=".15s">
                            <div class="product-figure"><img src="images/product-1-161x162.png" alt="" width="161" height="162"/>
                            </div>
                            <div class="product-rating"><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star text-gray-13"></span>
                            </div>
                            <h6 class="product-title">Original</h6>
                            <h7 class="product-title">Pão delicioso, carne suculenta e queijo derretido.</h7>
                            <div class="product-price-wrap">
                                <div class="product-price">$15.00</div>
                            </div>
                            <div class="product-button">
                                <div class="button-wrap">
                                    <a class="button button-xs button-primary button-winona" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870&text=Eu%20quero%20este%20hamburger" target="_blank">
                                        Peça pelo Whatsapp
                                    </a>
                                </div>
                                <div class="button-wrap">
                                    <a class="button button-xs button-secondary button-winona" href="https://source.unsplash.com/0JYgd2QuMfw/1500x1000" data-fancybox data-caption="ORIGINAL - Pão delicioso, carne suculenta e queijo derretido.">
                                            Ver detalhes
                                    </a>
                                </div>
                            </div>
                            <span class="product-badge product-badge-new">#1</span>
                        </article>
                        

                    </div>
                    
                    <div class="col-sm-6 col-lg-4 col-xl-3">
                        <!-- Product-->
                        <article class="product wow fadeInLeft" data-wow-delay=".1s">
                            <div class="product-figure"><img src="images/product-2-161x162.png" alt="" width="161" height="162"/>
                            </div>
                            <div class="product-rating"><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span>
                            </div>
                            <h6 class="product-title">Original EGG</h6>
                            <div class="product-price-wrap">
                                <div class="product-price">$17.00</div>
                            </div>
                            <div class="product-button">
                                <div class="button-wrap">
                                    <a class="button button-xs button-primary button-winona" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870&text=Eu%20quero%20este%20hamburger" target="_blank">
                                        Peça pelo Whatsapp
                                    </a>
                                </div>
                                <div class="button-wrap">
                                    <a class="button button-xs button-secondary button-winona" href="https://source.unsplash.com/0JYgd2QuMfw/1500x1000" data-fancybox data-caption="This image has a caption">
                                            Ver detalhes
                                    </a>
                                </div>
                            </div>
                            <span class="product-badge product-badge-new">#2</span>
                        </article>
                    </div>
                    
                    <div class="col-sm-6 col-lg-4 col-xl-3">
                        <!-- Product-->
                        <article class="product wow fadeInLeft" data-wow-delay=".05s">
                            <div class="product-figure"><img src="images/product-3-161x162.png" alt="" width="161" height="162"/>
                            </div>
                            <div class="product-rating"><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star text-gray-13"></span>
                            </div>
                            <h6 class="product-title">Original BACON</h6>
                            <div class="product-price-wrap">
                                <div class="product-price">$17.00</div>
                            </div>
                            <div class="product-button">
                                <div class="button-wrap">
                                    <a class="button button-xs button-primary button-winona" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870&text=Eu%20quero%20este%20hamburger" target="_blank">
                                        Peça pelo Whatsapp
                                    </a>
                                </div>
                                <div class="button-wrap">
                                    <a class="button button-xs button-secondary button-winona" href="https://source.unsplash.com/0JYgd2QuMfw/1500x1000" data-fancybox data-caption="This image has a caption">
                                            Ver detalhes
                                    </a>
                                </div>
                            </div>
                            <span class="product-badge product-badge-new">#3</span>
                        </article>
                    </div>
                    
                    <div class="col-sm-6 col-lg-4 col-xl-3">
                        <!-- Product-->
                        <article class="product wow fadeInLeft">
                            <div class="product-figure"><img src="images/product-4-161x162.png" alt="" width="161" height="162"/>
                            </div>
                            <div class="product-rating"><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span>
                            </div>
                            <h6 class="product-title">Basicão</h6>
                            <div class="product-price-wrap">
                                <div class="product-price">$20.00</div>
                            </div>
                            <div class="product-button">
                                <div class="button-wrap">
                                    <a class="button button-xs button-primary button-winona" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870&text=Eu%20quero%20este%20hamburger" target="_blank">
                                        Peça pelo Whatsapp
                                    </a>
                                </div>
                                <div class="button-wrap">
                                    <a class="button button-xs button-secondary button-winona" href="https://source.unsplash.com/0JYgd2QuMfw/1500x1000" data-fancybox data-caption="This image has a caption">
                                            Ver detalhes
                                    </a>
                                </div>
                            </div>
                            <span class="product-badge product-badge-new">#4</span>
                        </article>
                    </div>
                    
                    <div class="col-sm-6 col-lg-4 col-xl-3">
                        <!-- Product-->
                        <article class="product wow fadeInLeft">
                            <div class="product-figure"><img src="images/product-5-161x162.png" alt="" width="161" height="162"/>
                            </div>
                            <div class="product-rating"><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span>
                            </div>
                            <h6 class="product-title">Sasá Burger</h6>
                            <div class="product-price-wrap">
                                <div class="product-price product-price-old">$29.00</div>
                                <div class="product-price">$25.00</div>
                            </div>
                            <div class="product-button">
                                <div class="button-wrap">
                                    <a class="button button-xs button-primary button-winona" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870&text=Eu%20quero%20este%20hamburger" target="_blank">
                                        Peça pelo Whatsapp
                                    </a>
                                </div>
                                <div class="button-wrap">
                                    <a class="button button-xs button-secondary button-winona" href="https://source.unsplash.com/0JYgd2QuMfw/1500x1000" data-fancybox data-caption="This image has a caption">
                                            Ver detalhes
                                    </a>
                                </div>
                            </div>
                            <span class="product-badge product-badge-new">#5</span>
                        </article>
                    </div>
                    
                    <div class="col-sm-6 col-lg-4 col-xl-3">
                        <!-- Product-->
                        <article class="product wow fadeInLeft">
                            <div class="product-figure"><img src="images/product-6-161x162.png" alt="" width="161" height="162"/>
                            </div>
                            <div class="product-rating"><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span><span class="mdi mdi-star"></span>
                            </div>
                            <h6 class="product-title">Paulu's Burger</h6>
                            <div class="product-price-wrap">
                                <div class="product-price product-price-old">$29.00</div>
                                <div class="product-price">$25.00</div>
                            </div>
                            <div class="product-button">
                                <div class="button-wrap">
                                    <a class="button button-xs button-primary button-winona" href="http://api.whatsapp.com/send?1=pt_br&phone=5527981641870&text=Eu%20quero%20este%20hamburger" target="_blank">
                                        Peça pelo Whatsapp
                                    </a>
                                </div>
                                <div class="button-wrap">
                                    <a class="button button-xs button-secondary button-winona" href="https://source.unsplash.com/0JYgd2QuMfw/1500x1000" data-fancybox data-caption="This image has a caption">
                                            Ver detalhes
                                    </a>
                                </div>
                            </div>
                            <span class="product-badge product-badge-new">#6</span>
                        </article>
                    </div>
                    
                </div>
            </div>
        </section>

        
        <div id="modal01" class="w3-modal" onclick="this.style.display='none'">
            <span class="w3-button w3-hover-red w3-xlarge w3-display-topright">&times;</span>
            <div class="w3-modal-content w3-animate-zoom">
                <img id="img01" style="width:100%">
            </div>
        </div>
        
<script>
    function onClick(element) {
      document.getElementById("img01").src = element.src;
      document.getElementById("modal01").style.display = "block";
    }
</script>
        
        
        
        
        
        

        <!-- What People say-->
        <section class="section section-xl bg-default">
            <div class="container">
              <h3 class="wow fadeInLeft">O que estão dizendo</h3>
            </div>
            <div class="container container-style-1">
              <div class="owl-carousel owl-style-12" data-items="1" data-sm-items="2" data-lg-items="3" data-margin="30" data-xl-margin="45" data-autoplay="true" data-nav="true" data-center="true" data-smart-speed="400">
                <!-- Quote Tara-->
                <article class="quote-tara">
                  <div class="quote-tara-caption">
                    <div class="quote-tara-text">
                      <p class="q">PizzaHouse is the longest lasting pizza place in the city and is well run and staffed. Prices are great and allow me to keep coming back.</p>
                    </div>
                    <div class="quote-tara-figure"><img src="images/user-6-115x115.jpg" alt="" width="115" height="115"/>
                    </div>
                  </div>
                  <h6 class="quote-tara-author">Ashley Fitzgerald</h6>
                  <div class="quote-tara-status">Client</div>
                </article>
                <!-- Quote Tara-->
                <article class="quote-tara">
                  <div class="quote-tara-caption">
                    <div class="quote-tara-text">
                      <p class="q">I am a real pizza addict, and even when I’m home I prefer your pizzas to all others. They taste awesome and are very affordable.</p>
                    </div>
                    <div class="quote-tara-figure"><img src="images/user-8-115x115.jpg" alt="" width="115" height="115"/>
                    </div>
                  </div>
                  <h6 class="quote-tara-author">Stephanie Williams</h6>
                  <div class="quote-tara-status">Client</div>
                </article>
                <!-- Quote Tara-->
                <article class="quote-tara">
                  <div class="quote-tara-caption">
                    <div class="quote-tara-text">
                      <p class="q">PizzaHouse has amazing pizza. Not only do you get served with a great attitude, you also get delicious pizza at a great price!</p>
                    </div>
                    <div class="quote-tara-figure"><img src="images/user-7-115x115.jpg" alt="" width="115" height="115"/>
                    </div>
                  </div>
                  <h6 class="quote-tara-author">Bill Johnson</h6>
                  <div class="quote-tara-status">Client</div>
                </article>
                <!-- Quote Tara-->
                <article class="quote-tara">
                  <div class="quote-tara-caption">
                    <div class="quote-tara-text">
                      <p class="q">PizzaHouse has great pizza. Not only do you get served with a great attitude and delivered delicious pizza, you get a great price.</p>
                    </div>
                    <div class="quote-tara-figure"><img src="images/user-9-115x115.jpg" alt="" width="115" height="115"/>
                    </div>
                  </div>
                  <h6 class="quote-tara-author">Aaron Wilson</h6>
                  <div class="quote-tara-status">Client</div>
                </article>
              </div>
            </div>
        </section>

    

   
  
      <!-- Page Footer-->
      <footer class="section footer-modern context-dark footer-modern-2">
        <div class="footer-modern-line">
          <div class="container">
            <div class="row row-50">
              <div class="col-lg-4 col-xl-5">
                <h5 class="footer-modern-title oh-desktop"><span class="d-inline-block wow slideInLeft">Newsletter</span></h5>
                <p class="wow fadeInRight">Assine nosso canal de comunicação para ficar por dentro de todas as novidades.</p>
                <!-- RD Mailform-->
                <form class="rd-form rd-mailform rd-form-inline rd-form-inline-sm oh-desktop" data-form-output="form-output-global" data-form-type="subscribe" method="post" action="bat/rd-mailform.php">
                  <div class="form-wrap wow slideInUp">
                    <input class="form-input" id="subscribe-form-2-email" type="email" name="email" data-constraints="@Email @Required"/>
                    <label class="form-label" for="subscribe-form-2-email">Digite seu E-mail</label>
                  </div>
                  <div class="form-button form-button-2 wow slideInRight">
                    <button class="button button-sm button-icon-3 button-primary button-winona" type="submit"><span class="d-none d-xl-inline-block">Subscribe</span><span class="icon mdi mdi-telegram d-xl-none"></span></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="footer-modern-line-2">
          <div class="container">
            <div class="row row-30 align-items-center">
              <div class="col-sm-6 col-md-7 col-lg-4 col-xl-4">
                <div class="row row-30 align-items-center text-lg-center">
                  <div class="col-md-7 col-xl-6"><a class="brand" href="index.html"><img src="images/logo-inverse-198x66.png" alt="" width="198" height="66"/></a></div>
                  <div class="col-md-5 col-xl-6">
                    <div class="iso-1"><span><img src="images/like-icon-58x25.png" alt="" width="58" height="25"/></span><span class="iso-1-big">9.4k</span></div>
                  </div>
                </div>
              </div>
                <div class="col-sm-6 col-md-12 col-lg-8 col-xl-8 oh-desktop" id="contatos">
                <a href="#contatos">.</a>
                <div class="group-xmd group-sm-justify">
                  <div class="footer-modern-contacts wow slideInUp">
                    <div class="unit unit-spacing-sm align-items-center">
                      <div class="unit-left"><span class="icon icon-24 mdi mdi-phone"></span></div>
                      <div class="unit-body"><a class="phone" href="tel:#">+55 27 9 8164-1870</a></div>
                    </div>
                  </div>
                  <div class="footer-modern-contacts wow slideInDown">
                    <div class="unit unit-spacing-sm align-items-center">
                      <div class="unit-left"><span class="icon mdi mdi-email"></span></div>
                      <div class="unit-body"><a class="mail" href="mailto:#">sempreburger@gmail.com.br</a></div>
                    </div>
                  </div>
                  <div class="wow slideInRight">
                    <ul class="list-inline footer-social-list footer-social-list-2 footer-social-list-3">
                      <li><a class="icon mdi mdi-instagram" href="#"></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="footer-modern-line-3">
          <div class="container">
            <div class="row row-10 justify-content-between">
              <div class="col-md-6"><span>Vila Velha - ES</span></div>
              <div class="col-md-auto">
                <!-- Rights-->
                <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span><span></span><span>.&nbsp;</span><span>All Rights Reserved.</span><span> Design&nbsp;by&nbsp;<a href="#">Paulo Franco</a></span></p>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
 
    <!-- Optional JavaScript -->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="assets/js/core.min.js"></script>
    <script src="assets/js/script.js"></script>
    <script src="assets/js/jquery.fancybox.min.js"></script>
    <!-- coded by Himic-->
    
    </body>
</html>